<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><div>
<p>An on-line editor and documentation about creating your own web gadgets will be available soon. A preview of what is to come can be seen below</p>
<div id="gadgetdemodiv" style="text-align: center; height:600px; vertical-align: middle">
<p><iframe style="display: none" width="700px" frameborder="0" height="600px" src="http://appdb.egi.eu/gadgets/gadgets.php?op=appdb.applications.list&amp;oppars=pagelength:5;pageoffset:0&amp; vpars=title:Applications%20Database"></iframe></p>
</div>
<p>You can add the above gadget in your webpage, by copying and pasting the code below:</p>
<div style="font-family: fixed">
<b><?php echo $this->escape('<p><iframe width="700px" frameborder="0" height="600px" src="http://appdb.egi.eu/gadgets/gadgets.php?op=appdb.applications.list&oppars=pagelength:5;pageoffset:0&vpars=title:Applications%20Database"></iframe></p>');?></b>
</div>
</div>
<script type="text/javascript">
showAjaxLoading();
$("#gadgetdemodiv").find("iframe").load(function(){
	hideAjaxLoading();
	$(this).fadeIn();
});
</script>
