<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><table width="100%" border="0" class="voresources">
<?php
if (isset($this->entry)) {
	foreach($this->entry as $k=>$v) {
		if( strtolower(trim($k)) == "notes"){
			$notes = "-";
			if( trim($v) === "" ){
				continue;
			}
			echo '<tr><td colspan="3" style="text-align:left;"><span><b>'.htmlspecialchars($k).'</b></span><span class="sep">:</span><span>'.htmlspecialchars($v).'</td></tr>';
		}else{
			echo '<tr><td style="width: 180px;text-align: right;"><b>'.htmlspecialchars($k).'</b></td><td class="sep">:</td><td>'.htmlspecialchars($v).'</td></tr>';
		}
	}
}
?>
</table>
