#!/bin/bash
i=""
f=cat
case $1 in
	"-i")i="-i"; shift;;
	"-f")f="sed -e 's/:/ :/' | awk '{print \$1}' | sort -u";shift;;
esac
if [[ "$1" == "" ]]; then
	echo "Search in php, phtml, and js files for the provided text"
	echo "Usage: $0 [OPTION]... TEXT"
	echo 
	echo "  -i"
	echo "	performs a case insensitive search"
	echo "  -f"
	echo "	print only matching filenames, instead of matching lines"
else
	find \( -name \*.php -o -name \*.phtml -o -name \*.js \) -exec grep --color=always -H $i "$1" '{}' \;|eval $f|less -r
fi
