<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><?php if ($this->session->username === null) { ?>
<script type="text/javascript">
window.location='/';
</script>
<?php } ?>
<center>
<div id="detailsdlgcontent0" style="max-width:800px">
</div>
</center>
<script type="text/javascript">
function getComputedHeight(theElt){
        if(is_ie()){
                tmphght = document.getElementById(theElt).offsetHeight;
        }
        else{
                docObj = document.getElementById(theElt);
                var tmphght1 = document.defaultView.getComputedStyle(docObj, "").getPropertyValue("height");
                tmphght = tmphght1.split('px');
                tmphght = tmphght[0];
        }
        return tmphght;
};
var dialogCount=0;
</script>
<script type="text/javascript">
$("#detailsdlgcontent0").load("/people/details?id=0&dc="+dialogCount);
onEdit();
</script>
