<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><center>
<h3>Access Restricted</h3>
</center>
<div style="width:70%; margin-left:15%; margin-right:15%; text-align: justify">
<p>Authenticated write access to the EGI Applications Database is currently restricted to National Representatives, who are welcome to request access and register software on behalf of their NGI. <b>If you wish to gain write access to AppDB on behalf of your NGI</b>, please make sure you have an <a href="https://www.egi.eu/sso/" target="_blank">EGI SSO account</a> first, and then apply for access in an <a href="http://helpdesk.egi.eu/" target="_blank">EGI Helpdesk</a> ticket, by specifying "AppDB write access request" in the "Short description" field, and stating the NGI you represent, as well as your SSO username, in the description field below.
<br/><br/>
After a 2 month long trial period write access will be available to any individual who already has an EGI SSO account. Thank you for your understanding.</p></div>
<br/>
<center>
<p><a href="http://<?php echo $_SERVER['HTTP_HOST'];?>/">Return to the EGI Applications Database home page</a></p>
</center>
