<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_AccessTokenNetfiltersBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'access_token_netfilters';
	protected $_primary = array('tokenid', 'netfilter');
	protected $_sequence = false;
}
