<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_APIKeyNetfiltersBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'apikey_netfilters';
	protected $_primary = array('keyid', 'netfilter');
	protected $_sequence = false;
}
