<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_AppArchsBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'app_archs';
	protected $_primary = array('appid', 'archid');
	protected $_sequence = false;
}
