<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_AppContactMiddlewaresBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'appcontact_middlewares';
	protected $_primary = array('appid', 'researcherid', 'appmiddlewareid');
	protected $_sequence = false;
}
