<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_AppContactOtherItemsBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'appcontact_otheritems';
	protected $_primary = array('appid', 'researcherid', 'item');
	protected $_sequence = false;
}
