<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_AppContactVOsBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'appcontact_vos';
	protected $_primary = array('appid', 'researcherid', 'void');
	protected $_sequence = false;
}
