<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_AppManualCountriesBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'appmanualcountries';
	protected $_primary = array('appid', 'countryid');
	protected $_sequence = false;
}
