<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_AppOSesBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'app_oses';
	protected $_primary = array('appid', 'osid');
	protected $_sequence = false;
}
