<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_AppProgLangsBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'appproglangs';
	protected $_primary = array('appid', 'proglangid');
	protected $_sequence = false;
}
