<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_AppReleaseCountBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'app_release_count';
	protected $_primary = '';
	protected $_sequence = false;
}
