<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_DisciplinesBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'disciplines';
	protected $_primary = 'id';
	protected $_sequence = false;
}
