<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_PendingAccountsBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'pending_accounts';
	protected $_primary = 'id';
	protected $_sequence = true;
}
