<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_PplProgLangsBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'pplproglangs';
	protected $_primary = array('researcherid', 'proglangid');
	protected $_sequence = false;
}
