<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_ResearchersAppsBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'researchers_apps';
	protected $_primary = array('appid', 'researcherid');
	protected $_sequence = false;
}
