<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_SitesBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'sites';
	protected $_primary = 'guid';
	protected $_sequence = false;
}
