<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_VMISupportedContextFormatsBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'vmi_supported_context_fmt';
	protected $_primary = array('fmtid', 'vmiinstanceid');
	protected $_sequence = false;
}
