<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_VOContactsBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'vo_contacts';
	protected $_primary = '';
	protected $_sequence = false;
}
