<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Default_Model_DbTable_VOMSesBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'vomses';
	protected $_primary = array('void', 'hostname');
	protected $_sequence = false;
}
