<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><?php header('Content-type: application/atom+xml'); ?>
<?php echo '<?xml version="1.0" encoding="utf-8"?>'; ?>
<feed xmlns="http://www.w3.org/2005/Atom">
        <id><?php echo "http://".$_SERVER['APPLICATION_UI_HOSTNAME']."/"; ?></id>
        <title><?php echo htmlspecialchars((isset($this->request->title)?$this->request->title:$this->request->name)); ?></title>
        <subtitle><?php echo htmlspecialchars((isset($this->request->title)?$this->request->title:$this->request->name)); ?></subtitle>
    <icon><?php echo "http://".$_SERVER['APPLICATION_UI_HOSTNAME']."/images/EGI-logo_small.png";?></icon>
    <logo><?php echo "http://".$_SERVER['APPLICATION_UI_HOSTNAME']."/images/appdb-logo.png";?></logo>
        <link href="http://<?php echo $_SERVER['APPLICATION_UI_HOSTNAME']; ?>/"/>
        <author>
                <name>EGI Applications database</name>
        </author>
        <updated><?php echo date('c'); ?></updated>
        <?php foreach($this->entries as $e){
        $d = NewsFeed::parseEntry($e);
		if (array_keys($d) !== range(0, count($d) - 1)) {
			$d = array($d);
		}
		if(count($d) == 0 ) continue;
		for($i=0; $i< count($d); $i+=1){
			$n = $d[$i];
        ?><entry>
                <title><?php echo htmlspecialchars($n["title"]); ?></title>
                <link href="<?php echo $n["link"]; ?>"/>
                <id><?php echo "http://".$e->subjecttype."/".$e->id."/".$e->action; ?></id>
                <updated><?php 
					if( array_key_exists("timestamp",$n) === true){
						echo date('c',strtotime($n["timestamp"])); 
					}else{
						echo date('c',strtotime($e->timestamp)); 
					}
					
				?></updated>
                <summary type="html"><?php echo htmlspecialchars($n["html"]); ?></summary>
        </entry>
		<?php } ?>
        <?php } ?>
</feed>