<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><?php
	if($this->export===true){
		
	}else if(isset($this->error)){
		echo '<div id="linkStatuses" style="width:100%;height:100%;">'.$this->error.'</div>';
	}else{
		$host = "http://".$_SERVER["HTTP_HOST"];
	?>
<div class="aboutpage">
	<div class="aboutheader">
		<span><a href="<?php echo $host . "/pages/admin/brokenlinks"; ?>" target="_blank">permalink</a></span>
		<h1>Broken links report</h1>
		<hr>
	</div>
	<div id="linkStatuses" style="width:100%;height:100%;">
					<?php if ( $this->regional != '' ) echo '<span><h3>Regional Report for <i>' . $this->regional . '</i></h3></span>'; ?>
	<table width="100%" cellpadding="0" cellspacing="0" style="table-layout: fixed;width:100%;height:99%">
		<tbody>
			<tr style="height:10px;">
				<td style="padding-top:0px;">
				<div style="float:right; padding-right: 10px;padding-bottom:5px;text-align: right;padding-top:2px;margin: 15px 0px;">
					<ul style="list-style: none;display:inline-block;padding:0px;margin:0px;padding-bottom: 3px;">
						<li style="display:inline;"><span ><a href="/news/linkstatus?format=csv" title="click to download the report in csv format">download CSV</a></span></li>
					</ul>
					<div >There were <b><?php echo $this->total;?></b> broken links detected <?php if(isset($this->lastscan)){ echo 'at <b>' . $this->lastscan . '</b>';}?></div>
				</div>
				<div style="float:left;padding-top:5px;">
					<form action="#" id="linkStatuses_form" style="margin:15px 0px;padding:0px;padding-bottom:5px; padding-left: 15px;">
						<label for="linkStatuses_quicksearch">Search in report:</label>
						<input type="text" id="linkStatuses_quicksearch"/>
					</form>
				</div>
				<table  cellpadding="4" cellspacing="0" class="tablesorter" id="linkStatuses_tableheader" style="table-layout:fixed;width:810px;margin:0 auto;background-color: white;overflow: hidden">
					<thead style="background-color:#eee;color:#666666;font-weight: bold;cursor: default;">
						<tr style="padding:0px;">
							<th SCOPE=col style="width:20%;" >Link Type</th>
							<th SCOPE=col style="width:35px;">ID</th>
							<th SCOPE=col style="width:10%;">Name</th>
							<th SCOPE=col style="width:10%;">Owner</th>
							<th SCOPE=col style="width:15%;">e-mail</th>
							<th SCOPE=col style="width:5%;">URL</th>
							<th SCOPE=col>Description</th>
							<th SCOPE=col style="width:100px;">Since</th>
							<th title="Whitelisted" SCOPE=col style="width:5%">WL</th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
				</td>
			</tr>
			<tr style="width:100%;height:100%;">
				<td style="width:100%;">
				<div id="linkStatuses_body" style="overflow:auto;overflow-x:visible;overflow-y:auto;width:100%;display:inline-block;padding-top:-20px;zoom: 1;">
					<div>
				<table  cellpadding="4" cellspacing="0" id="linkStatuses_results" style="table-layout:fixed;width:810px;height:100%;margin: 0 auto;margin-top:-20px;padding:0px;" class="tablesorter">
					<thead style="visibility: hidden;top:0px;">
						<tr style="padding:0px;">
							<th SCOPE=col style="width:20%;" >Link type</th>
							<th SCOPE=col style="width:35px;">Id</th>
							<th SCOPE=col style="width:10%;">Name</th>
							<th SCOPE=col style="width:10%;">Owner</th>
							<th SCOPE=col style="width:15%;">E-mail</th>
							<th SCOPE=col style="width:5%;">Url</th>
							<th SCOPE=col>Description</th>
							<th SCOPE=col style="width:100px;">Since</th>
							<th title="Whitelisted" SCOPE=col style="width:5%">WL</th>
						</tr>
					</thead>
					<tbody >
						<?php
						$odd = false;
						foreach($this->entries as $entry){
							$odd = !$odd;
							$entry->url = str_replace("'", "%27", $entry->url);
							$entry->url = str_replace('"', "%22", $entry->url);
							$apppermalink = $host . "/?p=" . base64_encode('/apps/details?id='.$entry->appid);
							$hasowner = (trim($entry->ownerid)!=="")?true:false;
							$pplpermalink = $host . "/?p=" . base64_encode('/people/details?id='.$entry->ownerid);
							?>
							<tr style="vertical-align:super;<?php echo ($odd===true)?'background-color: #f5f5f5;':'';?>">
								
								<td style="vertical-align: top;">
						<?php
								$imgsrc = "/images/app.png";
								$imgtitle= "Software url";
								if($entry->linktype==="DOC"){
									$imgsrc = "/images/pub.png";
									$imgtitle= "Publication url";
								}

								?><img alt="" title="<?php echo $imgtitle; ?>" src="<?php echo $imgsrc; ?>" width="20"  />
							<?php echo (trim($entry->title)==="")?"<i>no title</i>":$entry->title; ?></td>
								<td><?php echo $entry->appid?></td>
								<td><a href='<?php echo $apppermalink;?>' title='Click to open the software' target="_blank"><?php echo $entry->appname; ?></a></td>
								<td><?php if($hasowner===true){?>
									<a href='<?php echo $pplpermalink;?>' title='Click to open the profile' target="_blank"><?php echo $entry->ownername; ?></a>
									<?php } else { echo ""; } ?>
								</td>
								<td><div style="overflow:hidden;padding:0px 2px 0px 2px;"><?php echo $entry->contact;?></div></td>
								<td><div style="overflow:hidden;width:100%;"><a href="<?php echo $entry->url; ?>" title="Click to open the url <?php echo $entry->url;?>" target="_blank"><?php echo (strlen($entry->url)>23)?substr($entry->url, 0,20) . "...":$entry->url; ?></a></div></td>
								<td><?php echo htmlspecialchars($entry->result); ?></td>
								<td><?php
									$l = strtotime($entry->firstchecked);
									$s = strtotime($entry->lastchecked);
									$dd = round(($s - $l) / 3600 / 24);
									if ( $dd == 0 ) {
										echo '<i>new entry</i>';
									} else {
										echo "$dd day(s)";
									}
								?></td>
								<td><a title="Toggle whitelisting state" href="#" onclick="appdb.utils.toggleURLWhitelistItem('<?php echo $entry->url; ?>', this);"><?php if ($entry->whitelisted) echo 'YES'; else echo 'NO';?></a></td>
							</tr>
						<?php } ?>

					</tbody>
				</table>
						</div>
				</div>
				</td>
			</tr>
		</tbody>
	</table>
	<?php if ( $this->total === 0 ) echo '<span><i>No broken links detected' . ($this->regional == '' ? '' : ' for ' . $this->regional . '</i>') . '</span>'; ?>
	</div>
	<script type="text/javascript" src="/js/jquery.quicksearch.js" ></script>
	<script type="text/javascript" src="/js/jquery.tablesorter.js"></script>
	<script type="text/javascript" >
		// add parser through the tablesorter addParser method 
		$.tablesorter.addParser({ 
			// set a unique id 
			id: 'brokensince', 
			is: function(s) { 
				// return false so this parser is not auto detected 
				return false; 
			}, 
			format: function(s) { 
				// format your data for normalization
				if(s.indexOf('new entry')>-1 || s.indexOf('day(s)')>-1){
					var nums = s.toLowerCase().replace(/new\ entry/,"0").match(/\d+/g);
					nums = $.isArray(nums)?nums[0]:"0";
					var len = 10 - nums.length;
					var zeros = "";
					for(var i=0; i<len; i+=1){
							zeros += "0";
					}
					return zeros + nums;
				}
				return s;


			}, 
			// set type, either numeric or text 
			type: 'text' 
		}); 

		 $(function() { 
		$("#linkStatuses_tableheader").tablesorter({ 
				headers: { 
					7: { 
						sorter:'brokensince' 
					} 
				}
			});
		$("#linkStatuses_results").tablesorter({ 
				headers: { 
					7: { 
						sorter:'brokensince' 
					} 
				}
			});
			$("#linkStatuses_form").keypress(function(event){if(event.which== 13){return false;}});
		 });
	</script>
	<?php } ?>
</div>