<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <style type="text/css"><!--
body {
    font-family: Helvetica,Arial, sans-serif;
    font-size: 14px;
    max-width : 1192px;
}
.mailcontainer{
    width:100%;
    max-width : 1192px;
	text-align: left;
}
.mailheader{
    width:100%;
    border-bottom: #999999 1px solid;
    padding:0px;
    margin :0px;
    max-width : 1192px;
}
.mailbody{
    border: #999999 1px solid;
    background-color: whitesmoke;
    margin-top:2px;
    margin-bottom : 2px;
    max-width : 1192px;
}
.mailsub {
    padding-bottom: 10px;
}

.mailsubbody{
     padding-left:10px;
}
.mailnews{
    border-top: #dcdcdc 1px dashed;
    padding-bottom : 5px;
    padding-top : 2px;
}
.mailnews div{
    vertical-align: middle;
}
.mailnewsheader{
    display : inline-block;
    width:100%;
    height:30px;
}
.mailnewsimg{
    display : inline-block;
}
.mailnewsimg img {
    width:30px;
}
.mailnewstitle{
    display : inline-block;
    font-weight: bold;
    vertical-align: middle;
}
.mailnewstitle a{
    text-decoration: none;
    color : #2A2A2A;
}
.mailnewstitle a:hover{
    color : #D96B00;
}

.mailnewssummary{
    padding-left :35px;
    font-size: 18px;
}
.mailnewssummary img {
    padding-right : 5px;
}
.mailnewssummary a {
    text-decoration: none;
    color : #D96B00;
}
.mailnewssummary a:hover {
    text-decoration: underline;
}
.mailfooter{
    display : block;
    text-align: center;
    background-color: whitesmoke;
    padding:5px;
}
.mailfooter span{
    font-size: 12px;
    color:gray;
}
.mailfooter a{
    text-decoration: none;
    color : #D96B00;
}
.mailfooter a:hover{
    text-decoration: underline;
}
.iasa{
    display:block;
    text-decoration:none;
    text-align: center;
    color:whitesmoke;
    font-size:12px;
    padding:3px;
}
.iasa:hover{
    color : #fe5e01;
}
.iasa:visited{
    color:whitesmoke;
}
-->
        </style>
    </head>
    <body>
        <center>
        <table class="mailcontainer" border="0" cellpadding="0" cellspacing="0">
            <tbody>
                <tr style="height:90px;">
                    <td>
                        <div class="mailheader" style="height:90px;">
                            <div style="height:90px;width:100%;vertical-align: middle;background-image: url('<?php echo $this->server; ?>images/header_back70.png');background-position: left center;background-repeat: no-repeat">
                                        <div align="left" style="float:left;top:10px;position:relative;">
                                            <a target="_blank" href="http://www.egi.eu/">
                                                <img border="0" style="" src="<?php echo $this->server; ?>images/EGI-logo_small.png" alt=""  />
                                            </a>
                                        </div>
                                        <div id="egimoto" style="float:left;">
                                            <a target="'_blank" href="<?php echo $this->server; ?>"><img border="0" src="<?php echo $this->server; ?>images/appdb-logo.png" alt="" /></a>
                                            <h1 style="margin:0px;padding:0px;color :#2a2a2a">Role verification request</h1>
                                        </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="mailbody">
                            <div class="mailsub">
                                <div class="mailsubbody">
                                   <div class="mailnews">
                                        <div class="mailnewssummary">
											<table cellpadding="0" cellspacing="0">
												<tbody>
													<tr>
														<td style="width:105px;">
															<span class="mailnewsimg"><img src="<?php echo $this->server . 'people/getimage?id=' . $this->entry->id;  ?>" alt="" border="0" style="width:50px;height:50px;"/></span>
														</td>
														<td>
															<div>User <b><?php echo $this->entry->firstName . " " . $this->entry->lastName ?></b> has requested the AppDB role of <i><b><?php
																echo $this->entry->positionType->description;
																?></b></i> and needs to be verified as one.
																For further information visit the user's <a href='<?php echo $this->server . '?p='.base64_encode('/people/details?id='.$this->entry->id);?>' title='Click to view the profile' target='_blank'>profile</a> or click <a href="<?php echo $this->server . "people/authorizerole?p=".$this->entry->roleVerificationPass; ?>" target="_blank" title="Click to authorize user's request">here</a> to directly authorize the request.</div>
														</td>
													</tr>
												</tbody>
											</table>
										</div>
                                    </div>
                                </div>
                                <div class="mailitemfooter"></div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <a class="iasa" href="http://www.iasa.gr/" target="_blank"><font>&copy; Institute of Accelerating Systems and Applications</font>, 2009-<?php echo date("Y");?>, Athens, Greece</a>
                    </td>
                </tr>
            </tbody>
        </table>
        </center>
    </body>
</html>
