<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><?php header('Content-type: application/rss+xml'); ?>
<?php echo '<?xml version="1.0" encoding="utf-8"?>'; ?>
<rss version="2.0" >
<channel>
        <ttl>10</ttl>
        <title><?php echo htmlspecialchars((isset($this->request->title)?$this->request->title:$this->request->name)); ?></title>
        <link><?php echo 'http://'.$_SERVER['APPLICATION_UI_HOSTNAME'] .'/'; ?></link>
        <description><?php echo htmlspecialchars((isset($this->request->title)?$this->request->title:$this->request->name)); ?></description>
        <lastBuildDate><?php echo date('D, d M Y H:i:s O'); ?></lastBuildDate>
        <language>en-us</language>
		<?php foreach($this->entries as $e){
			$d = NewsFeed::parseEntry($e);
			if(array_keys($d) !== range(0, count($d) - 1) ){
				$d = array($d);
			}
			if(count($d) == 0 ) continue;
			for($i=0; $i< count($d); $i+=1){
				$n = $d[$i];
		?><item>
            <title><?php echo $n["title"];?></title>
            <link><?php echo $n["link"]; ?></link>
            <guid isPermaLink="false"><?php echo $e->subjecttype.";".$e->id.";".$e->action; ?></guid>
            <pubDate>
				<?php
					if( array_key_exists("timestamp",$n) === true){
						echo date('D, d M Y H:i:s O',strtotime($n["timestamp"])); 
					}else{
						echo date('D, d M Y H:i:s O',strtotime($e->timestamp)); 
					}
				?>
			</pubDate>
            <description><?php echo htmlspecialchars($n["html"]); ?></description>
        </item>
		<?php } ?>
		<?php } ?>
</channel>
</rss>
