<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <style type="text/css">
body {
    font-family: Helvetica,Arial, sans-serif;
    font-size: 14px;
    max-width : 1192px;
}
.mailcontainer{
    width:100%;
    height : 100%;
    max-width : 1192px;
}
.mailheader{
    width:100%;
    border-bottom: #999999 1px solid;
    padding:0px;
    margin :0px;
    max-width : 1192px;
}
.mailbody{
    border: #999999 1px solid;
    background-color: whitesmoke;
    margin-top:2px;
    margin-bottom : 2px;
    max-width : 1192px;
}
.mailsub {
    padding-bottom: 10px;
}
.mailsubheader {
    background-color: #dcdcdc;
    border-bottom: #dcdcdc 1px solid;
    color : #2A2A2A;
    width:100%;
    display : inline-block;
}
.mailsubheader .name {
    display : inline;
}
.mailsubheader .name > h3{
    padding :0px;
    margin:0px;
    padding-left: 5px;
    display : inline-block;
}

.mailsubheader .toolkit{
    display : inline-block;
    float : right;
    padding:2px;
    padding-right: 5px;
}
.toolkit {
    font-size: 12px;
    width:200px;
    text-align: right;
}
.toolkit div{
    display : inline-block;
}
.toolkit .seperator{
    list-style: circle;
}
.toolkit .unsubscribe a{
    cursor : pointer;
    color : #fe5e01;
    text-decoration: none;
}
.toolkit .unsubscribe a:hover{
    text-decoration: underline;
    color : #D96B00;
}
.mailsubbody{
     padding-left:10px;
}
.mailnews{
    border-top: #dcdcdc 1px dashed;
    padding-bottom : 5px;
    padding-top : 2px;
}
.mailnews div{
    vertical-align: middle;
}
.mailnewsimg{
    display : inline-block;
}
.mailnewsimg img {
    width:30px;
}
.mailnewstitle{
    display : inline-block;
    font-weight: bold;
}
.mailnewstitle a{
    text-decoration: none;
    color : #2A2A2A;
}
.mailnewstitle a:hover{
    color : #D96B00;
}
.mailnewssummary{
    padding-left :35px;
}
.mailfooter{
    text-align: center;
    background-color: whitesmoke;
    padding:5px;
}
.mailfooter span{
    font-size: 12px;
}
        </style>
    </head>
    <body>
        <center>
        <table class="mailcontainer" border="0" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        <div class="mailheader">
                            <div style="height:90px;width:100%;vertical-align: middle;background-image: url('<?php echo $this->server; ?>images/header_back70.png');background-position: left center;background-repeat: no-repeat">
                                        <div align="left" style="float:left;top:10px;position:relative;">
                                            <a target="_blank" href="http://www.egi.eu/">
                                                <img border="0" style="" src="<?php echo $this->server; ?>images/EGI-logo_small.png" alt="" />
                                            </a>
                                        </div>
                                        <div id="egimoto" style="float:left;">
                                            <a target="'_blank" href="<?php echo $this->server; ?>"><img border="0" src="<?php echo $this->server; ?>images/appdb-logo.png" alt="" /></a>
                                            <h1 style="margin:0px;padding:0px;color :#2a2a2a">E-mail notification unsubscription</h1>
                                        </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="mailbody">
                            <?php if($this->result === 'ok') {?>
                                    <div><center><h2>You have been sucessfully unsubscribed from all <?php echo ($this->digest!=null)?$this->digest." ":""; ?>AppDB News e-mail notification lists'.</h2></center></div>
                            <?php } else if($this->result === 'none') {?>
                                    <div><center><h2>No subscriptions found or you have already been unsubscribed from all <?php echo ($this->digest!=null)?$this->digest." ":""; ?>AppDB News e-mail notification lists'.</h2></center></div>
                            <?php } else {?>
                                    <div><center><h2>There was an error processing your request. Please contact support through the <a href="http://helpdesk.egi.eu">EGI Helpdesk</a></h2></center></div>
                            <?php }?>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <a style="display:block;text-decoration:none;text-align: center;color:whitesmoke;font-size:12px;padding:3px;" href="http://www.iasa.gr/" target="_blank"><font>© Institute of Accelerating Systems and Applications</font>, 2009-<?php echo date("Y");?>, Athens, Greece</a>
                    </td>
                </tr>
            </tbody>
        </table>
        </center>
    </body>
</html>
