<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

namespace Application\Model\DbTable\Row;



class FAQsBase extends \Zend\Db\TableGateway\AbstractTableGateway
{

}
