<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><div><h3>Fields</h3></div>
<table>
    <tr>
        <td>ID</td><td>A number which uniquely identifies the entry</td>
    </tr>
    <tr>
        <td>Type</td><td>"Application" or "Tool"</td>
    </tr>
    <tr>
        <td>Name</td><td>The name of the software</td>
    </tr>
    <tr>
        <td>Description</td><td>A short text describing the software</td>
    </tr>
    <tr>
        <td>Discipline</td><td>The research field this software is related to</td>
    </tr>
    <tr>
        <td>URLs</td><td>A list of URLs which may provide documentation, support, download links, etc, about the software</td>
    </tr>
    <tr>
        <td>Abstract</td><td>An extended text providing more detailed information about the software</td>
    </tr>
    <tr>
        <td>Country</td><td>Software country of origin. Entries are inherited by the people that are referenced as contacts, or may be added explicitly</td>
    </tr>
    <tr>
        <td>VOs</td><td>A list of VOs that support this software</td>
    </tr>
    <tr>
        <td>Middleware</td><td>A list of middleware that this software works with</td>
    </tr>
    <tr>
        <td>Status</td><td>The state of the software, concerning grid deployment</td>
    </tr>
    <tr>
        <td>Related Contacts</td><td>A list of people who are responsible for the software, such as the developers who created it or who maintain it, etc.</td>
    </tr>
    <tr>
        <td></td><td></td>
    </tr>
    <tr>
        <td></td><td></td>
    </tr>
</table>
<div><h3>Usage</h3></div>
<table>
</table>
