<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><?php 
	$error = $this->error;
	$session = $this->session;
	$accounttype = $this->accounttype;
	$accountname = $this->accountname;
	$profilename = $this->profilename;
	$profileid = $this->id;
	
	if( $error != null ){
?>
<div class='sendconfirmationcode response error notifydialog display'>
	<div class="shade"></div>
	<div class="dialog">
		<div class="title"><img src="/images/vappliance/redwarning.png" alt="" /><span>Failed to send confirmation email</span></div>
		<div class='message'>
			<div>Could not send confirmation code to the profile <?php echo $this->profilename; ?> for the following reasons:</div>
			<div>
				<pre><?php echo $this->error; ?></pre>
			</div>
		</div>
		<div class="actions">
			<a class="action close iconttext" title="" onclick="$(this).closest('.notifydialog').remove();" >Close</a>
		</div>
	</div>
</div>
<?php } else { ?>
<div class='sendconfirmationcode response success notifydialog display'>
	<div class="shade"></div>
	<div class="dialog">
		<div class='title'><img src="/images/tick.png" alt=""><span>Successfully sent email connection request</span></div>
		<div class='message'>
			The connection request has been sent to the profile <?php echo $profilename; ?>. After closing this dialog, you will be prompted to enter a confirmation code.
			<br>
			<div style="font-size:11px;color:#666;padding-top:20px;"><b>Advice</b>: Please consider that there are cases where an email could be marked as spam by various email servers. Hence, you are strongly advised to have a look at your spam folder if you do see the email connection request in the next 2 minutes.</div>
		</div>
		<div class="actions">
			<a class="action close icontext" onclick="$(this).closest('.notifydialog').remove();">close</a>
		</div>
	</div>
</div>
<?php } ?>

