<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><script>
var findPeople = function(name) {
	$("#main").hide();
	showAjaxLoading();
	$.get("/people?filter=%7B%22name%22%3A %22"+name+"%22 %7D", {}, function(data,txtstatus) {
		hideAjaxLoading();
		if (data.indexOf('Nothing to display') == -1) {
			$("#main").html(data);
		} else {
			alert('No records found');
		}
		$("#main").fadeIn("fast");
	}, 'html');
}
</script>
<div>
	<table width="100%">
		<tr>
			<th style="width:10%; text-align: center">Role</th>
			<th style="text-align: left">Name</th>
		</tr>
<?php if (count($this->entries) > 0) foreach ($this->entries as $entry) { ?>
		<tr>
			<td style="text-align: center; width: 10%"><?php echo $entry['role']; ?></td>
			<td><a href="#" onclick="findPeople('<?php echo str_replace("'","\'",$entry['name']);?>');"><?php echo $entry['name']; ?></a></td>
		</tr>
<?php } ?>
	</table>
</div>
