<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><div id="metadata" style="display: none;">
	<input type="text" id="viewtype" value="vo"/>
	<input type="text" id="offset" value="0"></input>
	<input type="text" id="length" value="0"></input>
	<input type="text" id="gid" value=""></input>
	<input type="text" id="currentPage" value="0"></input>
</div>
<iframe style="display: none" id="voframe" src="/upload/vos.html"></iframe>
<div id="volst"></div>
<script type="text/javascript">
var lst=$("#volst");
var parseVOs = function() {
    alert('a');
    var s="";
    $(vos).contents().find('#vo_list').find("table.voTable").find("tr").each(function() {
        $(this).find("td").each(function() {
            if ($(this).index() == 1) { s=s+$(this).text()+" "; };
        });
        $(this).find("a.xmlLink").each(function(){
            s=s+"<a href='http://operations-portal.egi.eu"+$(this).attr("href")+"'>details</a><br/>";
        });
    });
    $("#volst").html(s);
};
var vos = document.getElementById('voframe');
$(vos).load(function() {
    parseVOs();
});
</script>
