<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><div id="metadata" style="display: none;">
    <input type="text" id="viewtype" value="ppl"/>
    <input type="text" id="offset" value="<?php echo $this->offset ?>" />
    <input type="text" id="length" value="<?php echo $this->length ?>" />
    <input type="text" id="gid" value="<?php echo $this->gid ?>" />
    <input type="text" id="currentPage" value="<?php echo $this->currentPage ?>" />
</div>
<div class="listcontainer people">
<table border="0" id="ppl_main_content" style="width:100%;height:100%">
    <tr style="height:20px;">
        <td colspan="3" style="max-height:20px;height:20px;width:100%">
			<div class="listcontainer-header">
				<div class="simpleFilter">
					<span  id="ppl_filter" style="white-space: nowrap; margin-left: 0; margin-right: auto"></span>
				</div>
				<div class="orderby">
					<div id="ppl_orderby" style="white-space: nowrap; vertical-align: middle; padding-right: 20px"></div>
				</div>
				<div id="ppl_viewbuttons" class="listtypebuttons" ></div>
				<div id="ppl_loading" class="loader" >
					<img src="/images/ajax-loader-small.gif" alt="" width="12px" height="12px" />
					<span >Loading...</span>
				</div>
				
			</div>
        </td>
    </tr>
    <tr >
		<td align="center" >
			<div class="refinedfiltering">
				<div id="ppl_managedfilters" class="managedfilter" >
					<span class="title">Filters:</span>
					<ul></ul>
					<a href="#" title="Display available filters" class="action display"><span>refine your search</span><span class="collapsed">|&#x25BC;</span><span class="expanded">|&#x25B2;</span></a>
					<a href="#" title="Clear all filters" class="action reset hidden"><img src="/images/cancelicon.png" alt="" /><span>clear all</span></a>
				</div>
				<div id="ppl_logisticsselector" class="logisticsselector" style="display: none"></div>
			</div>
			<div class="listmetadata">
				<div id="ppl_result_timer" ></div>
				<div id="ppl_permalink"></div>
			</div>
            <div id='ppl_paging' class="pager"></div>
        </td>
    </tr>
    <tr>
        <td colspan="3">
            <ul class="itemgrid" classname="itemgrid" id="pplmainlist"></ul>
        </td>
    </tr>
	<tr>
		<td>
			<div id='ppl_paging_bottom' class="pager"></div>
		</td>
	</tr>
</table>
<?php if (false) { //disabled ?>
<ul class="listtoolbox">
	<li><div id="pplexportdiv"></div><div class="description">EXPORT</div></li>
</ul>
<?php } ?>
</div>
