<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><script type="text/javascript">
	var filterPpl = function() {
		var key=$(':input[name="pplfilterbox"]:last').val();
		if ( key == "" ) {
			$(".mainlist:last li").show();
		} else {
			$(".mainlist:last li").hide();
			$(".mainlist:last li").each(function(x){
				var val=$(this).text();
				if ( val.toLowerCase().indexOf(key.toLowerCase()) != -1 ) $(this).show();
			});
		};
	};
	
	var saveChanges = function() {
		$(".mainlist:last li").show();
		var olddata=$("ul[id^='SciConDiv']:last");
		var newdata=$('ul.mainlist:last');
		//add existing people
		olddata.find('li').each(function(x){
			newdata.find('li[name="'+$(this).attr('name')+'"]').find('input').prop('checked', true);
		});
		//remove unselected from list
		$('ul.mainlist:last li').each(function(x){
			if ( $(this).find('input').attr('checked') == '' ) $(this).remove();
		});
		//update association list
		olddata.html(newdata.html());
		dijit.byId($('div.dijitDialog:last').attr('id')).onCancel();
	};
</script>
<div>
Filter: <span><input name="pplfilterbox" dojoType="dijit.form.TextBox"/><a href="#" onclick="filterPpl();"><img style="vertical-align: middle" border="0" src="images/search.png"/></a></span>
</div>
<hr/>
<div style="overflow-y: auto; max-height:400px;">
	<ul class="mainlist" className="mainlist">
	<?php
	for ($i=0; $i<$this->entry->count(); $i++) {
		$entry=$this->entry->items[$i];
		echo '<li name="scicon'.$entry->Id.'"><a title="'.$this->escape($entry->LastName.' '.$entry->FirstName).'" href="#" onclick="var a=$(this).parent().find(\'input\');if ( a.attr(\'checked\') == \'\' ) a.attr(\'checked\',\'checked\'); else a.attr(\'checked\',\'\');"><img border="0" src="/people/getimage?req='.urlencode($entry->lastUpdated).'&id='.$entry->Id.'" width="100px" height="100px"/>'.$this->escape($entry->LastName.' '.$entry->FirstName).'<span>'.$this->escape($entry->positionType->description).'<br/>'.$this->escape(substr($entry->institution,0,80));
		if (strlen($entry->institution)>80) echo "...";
		echo "</span></a><span align:'right'><input name='scicon".$entry->Id."' type='checkbox'/></span></li>";
	}
	?>
	</ul>
</div>
<div align="right" style="width:98%">
<button dojoType="dijit.form.Button" style="width:200px" onclick="saveChanges();">OK</button>
</div>
<script type="text/javascript">
	dojo.parser.parse($('div.dijitDialog:last')[0]);
</script>
