<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><div>
	<div id="reportabuse_title">
		Report problem
	</div>
	
	<div style="width:100%;height:100%;">
		<table width="100%" height="100%" cellpadding="5" >
			<tbody
				<tr style="padding:5px 0px 5px 0px;text-align: justify">
					<td colspan="2">
						<div id="reportabuse_description" class="reportabuse-description">
							You are about to make a report about this software. Please select the type of abuse and optionally add your comment. After submitting the report will be sent to be reviewed for validity and further processing.
						</div>
					</td>
				</tr>
				<tr>
					<td style="border-right: 1px black dashed;">
						<span class="reportabuse-types-title">Select the reason for your report:</span>
						<div id="reportabuse_types_application" class="reportabuse-types" style="display:none">
							<div class="reportabuse-type-item">
								<input type="radio" id="reportabuse_type_app_0" name="reportabuse_type_application" checked="checked" value="<?php echo AbuseController::REASON_INVALID_DATA; ?>" dojoType="dijit.form.RadioButton"/>
								<label for="reportabuse_type_app_0" >Invalid or false data</label>
							</div>
							<div class="reportabuse-type-item">
								<input type="radio" id="reportabuse_type_app_1" name="reportabuse_type_application" value="<?php echo AbuseController::REASON_INAPPROPRIATE_CONTENT; ?>" dojoType="dijit.form.RadioButton"/>
								<label for="reportabuse_type_app_1" >Inappropriate content</label>
							</div>
							
							<div class="reportabuse-type-item">
								<input type="radio" id="reportabuse_type_app_2" name="reportabuse_type_application" value="<?php echo AbuseController::REASON_OUT_OF_DATE; ?>" dojoType="dijit.form.RadioButton"/>
								<label for="reportabuse_type_app_2" >Out of date information</label>
							</div>
							<div class="reportabuse-type-item">
								<input type="radio" id="reportabuse_type_app_3" name="reportabuse_type_application" value="<?php echo AbuseController::REASON_BROKEN_LINK; ?>" dojoType="dijit.form.RadioButton"/>
								<label for="reportabuse_type_app_3" >Broken link</label>
							</div>
							<div class="reportabuse-type-item">
								<input type="radio" id="reportabuse_type_app_4" name="reportabuse_type_application" value="<?php echo AbuseController::REASON_SPELLING; ?>" dojoType="dijit.form.RadioButton"/>
								<label for="reportabuse_type_app_4" >Typo/Misspelling</label>
							</div>
							<div class="reportabuse-type-item">
								<input type="radio" id="reportabuse_type_app_5" name="reportabuse_type_application" value="<?php echo AbuseController::REASON_COPYRIGHT_ISSUE; ?>" dojoType="dijit.form.RadioButton" />
								<label for="reportabuse_type_app_5" >Copyright issue</label>
							</div>
							<div class="reportabuse-type-item">
								<input type="radio" id="reportabuse_type_app_6" name="reportabuse_type_application" value="<?php echo AbuseController::REASON_OTHER; ?>" dojoType="dijit.form.RadioButton"/>
								<label for="reportabuse_type_app_6" >Other</label>
							</div>
						</div>
						<div id="reportabuse_types_comment" class="reportabuse-types" style="display:none">
							<div class="reportabuse-type-item">
								<input type="radio" id="reportabuse_type_comment_0" name="reportabuse_type_comment" checked="checked" value="<?php echo AbuseController::REASON_INAPPROPRIATE_CONTENT; ?>" dojoType="dijit.form.RadioButton"/>
								<label for="reportabuse_type_comment_0" >Inappropriate content</label>
							</div>
							<div class="reportabuse-type-item">
								<input type="radio" id="reportabuse_type_comment_1" name="reportabuse_type_comment" value="<?php echo AbuseController::REASON_OTHER; ?>" dojoType="dijit.form.RadioButton"/>
								<label for="reportabuse_type_comment_1" >Other</label>
							</div>
						</div>
					</td>
					<td>
						<div >
							<span class="reportabuse-comment-title">Please provide a description of the problem:</span>
							<div class="reportabuse-comment" style="width:100%;" >
								<textarea id="reportabuse_comment" dojoType="dijit.form.SimpleTextarea" required="true" style="width:100%;height:200px;"></textarea>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div>
							<span id="reportabuse_submitting" style="float:left"></span>
							<span class="report-abuse-actions"style="float:right">
								<button id="reportabuse_submit" class="reportabuse-action" dojoType="dijit.form.Button" value="submit">submit</button>
								<button id="reportabuse_cancel" class="reportabuse-action" dojoType="dijit.form.Button" value="cancel">cancel</button>
							</span>
						</div>
					</td>
				</tr>

			</tbody>
		</table>
		
	</div>
	
</div>