<br /><br />
<div id="view-content" style="font-family:Arial">
	<?php 
		if($this->auth === true) {
			if(isset($this->error)){	
				print("<div style='padding: 10px;border: 1px solid #ddd;background: lightgoldenrodyellow;max-width:80%;display:block;'>");
				print("<div style='font-size:20px;font-weight:bold;padding-bottom:5px;'>" . htmlspecialchars($this->error, ENT_QUOTES, "UTF-8") . "</div><br>");
				print("" . $this->error_description . "<br>");
				print("</div>");
			} 
			else if ($this->done){
				print("You have successfully create a proxy certificate. You may close this window, now.");
			}
			else {
				$vo_text='';
				$vo=false;
				if (isset($_GET['appdbvo'])){
					$vo=$_GET['appdbvo'];
					$vo_text = " For the VO: <b>" . $vo . "</b>.";
				}
				$text="Please click <a style='padding: 4px;background: dodgerblue;color: white;border-radius: 6px;' href='".strtok($_SERVER["REQUEST_URI"],'?')."?appdbvo=".$vo."'>here</a> to obtain or renew your proxy cert.".$vo_text;
				print($text);
			}
		
		}
		else{
			print("<p>Not authenticated, please login to the EGI AppDB first.</p>");
	     	}	 
	?>
	<p><a href="javascript:window.close()">Close</a></p>	
</div>
