<br /><br />
<style>
  .modal {
    display: block;
    max-width: 580px;
    min-width: 580px;
    margin: 0 auto;
  }

  .modal > .header {
    font-size: 1.3em;
    line-height: 1.2857em;
    font-weight: 700;
    display: block;
    font-family: Arial,Helvetica,sans-serif;
    background: #FFF;
    margin: 0;
    padding: 1.25rem 1.5rem;
    box-shadow: none;
    color: rgba(0,0,0,.85);
    border-bottom: 1px solid rgba(34,36,38,.15);
  }
  
  .modal > * {
    padding: 10px;
  }

  .modal > .content {
    padding: 1.25em 1.5em;
  }
  .modal > .content.error {
    border: 1px solid #ddd;
    background: lightgoldenrodyellow;
  }
  
  .modal > .content .centered {
    margin: 0 auto;
    display: block;
  }
  
  .modal > .actions {
    text-align: center;
  }

  .button {
    cursor: pointer;
    display: inline-block;
    min-height: 1em;
    outline: 0;
    border: none;
    vertical-align: baseline;
    background: #E0E1E2;
    color: rgba(0,0,0,.6);
    font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
    margin: 0 .25em 0 0;
    padding: .78571429em 1.5em;
    text-transform: none;
    text-shadow: none;
    font-weight: 700;
    line-height: 1em;
    font-style: normal;
    text-align: center;
    text-decoration: none;
    border-radius: .28571429rem;
    box-shadow: 0 0 0 1px transparent inset, 0 0 0 0 rgba(34,36,38,.15) inset;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  .button.positive {
    background-color: green;
    color: white;
  }
  .button.positive:hover {
    background-color: #16ab39;
    color: #FFF;
    text-shadow: none;
  }
  .button.negative {
    background-color: #DB2828;
    color: #FFF;
    text-shadow: none;
    background-image: none;
  }
  .button.negative:hover {
    background-color: #d01919;
    color: #FFF;
    text-shadow: none;
  }
  .error_status {
    font-weight: bold;
  }
</style>
<div id="view-content" class="modal" style="font-family:Arial">
   <?php if($this->auth === true) {
           if(isset($this->error)){ ?>
                  <div class="header">An error occured</div>
		  <div class="content error" >
		    <div class="error_status"><?php echo htmlspecialchars($this->error, ENT_QUOTES, "UTF-8"); ?></div>
		    <div class="error_description"><?php echo $this->error_description; ?></div>
		  </div>
		  <div class="actions">
                    <a class="button negative" href="javascript:window.close()">Close</a>
                  </div>
	  <?php } else if ($this->done) { ?>
                  <div class="header">Success</div>
		  <div class="content">You have successfully obtained a new proxy certificate. You may close this window and proceed with the action.</div>
		  <div class="actions">
		    <a class="button negative" href="javascript:window.close()">Close</a>
                  </div>
          <?php } else {
	  	$vo_text='';
		$vo = false;
		if (isset($_GET['appdbvo'])){
			$vo = $_GET['appdbvo'];
			$vo_text = 'for VO: ' . $vo;
		}
		$url = strtok($_SERVER["REQUEST_URI"],'?') . "?appdbvo=" . $vo;
         ?>
		<div class="header">No proxy certificate <?php echo $vo_text; ?></div>
		<div class="content">
		  <p>In order to perform some actions, you will need to create a valid proxy certificate. It seems that either no proxy certificate has ever been created for you for the specific VO, or it has been expired.</p>
		  <p>To obtain or renew your proxy certificate click on the related button bellow and follow the instructions displayed. If you do not wish to proceed click the <i>cancel</i> button.</p>
                </div>
                <div class="actions">
		  <a class="button positive" href="<?php echo $url; ?>">Obtain new proxy certificate</a>
                  <a class="button negative" href="javascript:window.close()">Cancel</a>
                </div>
          <?php }
     } else { ?>
   	  <div class="header">Not authenticated</div>
          <div class="content">
            <p>In order to obtain a new proxy certificate you need to be authenticated as a valid user. </p><p>Please login to the EGI AppDB first.</p>
	  </div>
	  <div class="actions">
            <a class="button negative" href="javascript:window.close()">Close</a>
          </div>
  <?php } ?>
</div>
