<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><?php if( $this->error != "") { ?>
	<div class="createrelease template error">
		<span><?php echo $this->error; ?></span>
	</div>
<?php 
	return;
}?>
<div class="newrelease page">
	<div class="header">Please select the type of release:</div>
	<div class="content">
			<div class="selection basetype">
				<input type="radio" name="releasetypeselect" tabindex="0" value="base" align="left" id="basereleasetypeselect" />
				<label for="releasetypeselect">Base / Major release</label>
			</div>
			<div class="selection updatetype">
				<input type="radio" name="releasetypeselect" tabindex="0" value="base" align="left" id="updatereleasetypeselect" />
				<label for="basereleaseoption">An update release</label>
			</div>
			<div class="base releasetype">
				<div class="field displayversion">
					<label for="basereleasetag">Set release tag:</label>
					<input type="text" dojoType="dijit.form.ValidationTextBox" maxlength="20" name="basereleasetag" id="basereleasetag" required="true" />
					<span class="help">
						<img src="/images/question_mark.gif" alt=""/>
						<span class="message"></span>
					</span>
					<div class="indication" >
						<div class="checker hidden"><img src="/images/ajax-loader-small.gif" alt=""/><span >...validating</span></div>
						<div class="validation hidden" ><img src="/images/cancelicon.png" alt=""/><span class="value"></span></div>
					</div>
				</div>
				<div class="field repoarea">
					<label for="basereleasetag">Set base repository area for this base release - will be used for file system related tasks, only:</label>
					<span class="repoareacontent">
						<span class="repoareaprefix" />
						<span class="repoareatext">
							<input id="repoarea" name="repoarea" type="text" maxlength="20" dojoType="dijit.form.ValidationTextBox"/>
						</span>
						<span class="repoareasuffix">/&lt;OS&gt;/&lt;arch&gt;/</span>
					</span>
					<span class="help">
						<img src="/images/question_mark.gif" alt=""/>
						<span class="message"></span>
					</span>
					<div class="indication" >
						<div class="checker hidden"><img src="/images/ajax-loader-small.gif" alt=""/><span >...validating</span></div>
						<div class="validation hidden" ><img src="/images/cancelicon.png" alt=""/><span class="value"></span></div>
				</div>	</div>
			</div>
			<div class="update releasetype">
				<div class="field">
					<label for="associatedrelease">Select associated base release: </label>
					<select name="associatedrelease" id="associatedrelease" size="10" dojoType="dijit.form.Select" >
						<?php  for($i=0; $i < count($this->baselist); $i+=1){ $m=$this->baselist[$i]; ?>
						<option value="<?php echo $m["id"]; ?>" <?php echo ( ($i==0)?'selected="selected"':'' ); ?>><?php echo $m["displayVersion"];?> <?php echo '[area: ../' . strtolower($this->appName) . '/' . $m["repoAreaName"] . '/ ]' ; ?></option>
						<?php } ?>
					</select>
					<span class="help">
						<img src="/images/question_mark.gif" alt=""/>
						<span class="message"></span>
					</span>
				</div>
				<div class="field updatedisplayversion">
					<label for="updatereleasetag">Set release tag:</label>
					<input type="text" dojoType="dijit.form.ValidationTextBox" maxlength="20" name="updatereleasetag" id="updatereleasetag" required="required" />
					<span class="help">
						<img src="/images/question_mark.gif" alt=""/>
						<span class="message"></span>
					</span>
					<div class="indication" >
						<div class="checker hidden"><img src="/images/ajax-loader-small.gif" alt=""/><span >...validating</span></div>
						<div class="validation hidden" ><img src="/images/cancelicon.png" alt=""/><span class="value"></span></div>
					</div>
				</div>
				<div class="indication hidden" ></div>
			</div>
		
	</div>
	<div class="footer">
		<div class="actions">
			<button class="cancel" dojoType="dijit.form.Button" >Cancel</button>
			<button class="submit" dojoType="dijit.form.Button" disabled="disabled">Submit</button>
		</div>
	</div>
</div>