<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><html>
	<head>
		<link href="https://code.jquery.com/ui/1.11.3/themes/black-tie/jquery-ui.css" rel="stylesheet" type="text/css" />
		<link href="/elixir/ludo-jquery-treetable/css/jquery.treetable.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="/elixir/ludo-jquery-treetable/css/jquery.treetable.theme.default.css" />
		<style>
			body{
				position: relative;
				margin: 0 auto;
				max-width: 1024px;
				font-family: Arial;
				font-size: 14px;
			}
			body > h1{
				font-size: 22px;
				text-align: center;
			}
			.loader {
				display: inline-block;
				position: absolute;
				top: 0px;
				left: 5px;
				background-color: #CE0E0E;
				color: white;
				font-family: Arial;
				font-size: 14px;
				border-radius: 3px;
				padding: 3px 8px;
				line-height: 16px;
				vertical-align: middle;
			}
			.hidden {
				display: none;
			}
			td{
				vertical-align: top;
				padding-top: 3px;
			}
			td.treecell {
				width: 400px;
			}
			table.treetable tbody tr td.reportcell{
				width: 50px;
				text-align: center;
			}
			td.treecell,
			td.reportcell{
				border-right: 1px solid #DADADA;
			}
			td.actioncell button {
				display: none;
			}
			td.listcell .editlistcontainer {
				text-align: left;
				vertical-align: top;
			}
			td.listcell .editlistcontainer > *{
				vertical-align: top;
			}
			td.listcell .editlistcontainer ul {
				text-align: left;
				list-style: none;
				padding: 0px;
				margin: 0px;
				display: inline-block;
				width: 90%;
			}
			td.listcell .editlistcontainer ul > li {
				padding: 3px 5px;
			}
			td.listcell .editlistcontainer ul  li .id{
				font-weight: bold;
				color: #666;
			}
			td.actioncell {
				text-align: right;
				width: 40px;
			}
			tr:hover td.actioncell button{ 
				display: block;
			}
			.treetable tr > td.topic {
				min-height: 33px;
				height: 34px;
			}
			.treetable tr > td {
				border-bottom: 1px solid #E0E0E0;
				background-color: white;
			}
			.treetable tr:hover > td {
				background-color: #f0f0f0;
			}
			table.treetable tbody tr > td.treecell {
				cursor: default;
				padding: .3em .1em;
			}
			table.treetable tbody tr td span {
				padding: .2em 0 .2em .5em;
			}
			table.treetable span.indenter {
				width: 16px;
			}
			
			table.treetable tbody tr td.reportcell .topics {
				display: inline-block;
				visibility: hidden;
				padding: 0px;
				line-height: 12px;
				font-weight: normal;
				font-size: 12px;
				border: 1px solid #a0a0a0;
				border-radius: 2px;
				margin: 3px 1px;
				text-align: center;
				vertical-align: middle;
				position: relative;
			}
			table.treetable tbody tr td.reportcell .topics > span {
				padding: 2px;
				min-width: 15px;
				text-align: center;
				vertical-align: middle;
				display: inline-block;
			}
			table.treetable tbody tr td.reportcell .topics.local{
				color: white;
				background-color: #47A447;
				border-color: #398439;
			}
			table.treetable tbody tr td.reportcell .topics.children{
				color: white;
				background-color: #EE7836;
				border-color: #FA7106;
			}
			table.treetable tbody tr td.reportcell .topics.hasvalue{
				visibility: visible;
			}
			table.treetable tbody tr td.reportcell .topics:hover::before{
				content: attr(title);
				display: block;
				padding: 5px;
				background-color: white;
				border: 1px solid #a0a0a0;
				color: #333;
				position: absolute;
				bottom: 100%;
				min-width: 180px;
				text-align: left;
				
			}
			.dialog{
				position: fixed;
				display: none;
				width: 80%;
				height: 80%;
				z-index: 2000;
				padding: 5px;
				top: 0;
				left: 0;
				bottom: 0;
				right: 0;
				margin: 0 auto;
				max-width: 1024px;
				font-family: Arial;
				font-size: 14px;
			}
			body.showdialog .dialog{
				display: block;
			}
			.dialog > .shader{
				position: fixed;
				display: block;
				z-index: 2500;
				top: 0%;
				left: 0px;
				bottom: 0px;
				right: 0px;
				background-color: #aaa;
				 -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";
				filter: alpha(opacity=50);
				opacity: 0.5;
			}
			.dialog > .body{
				margin: 0 auto;
				position: relative;
				width: 1024px;
				max-width: 1024px;
				height: auto;
				z-index: 3000;
				margin-top: 5%;
				text-align: center;
				background: white;
				border: 1px solid #666;
				border-radius: 3px;
				padding-bottom: 35px;
				min-height: 350px;
				text-align: left;
			}
			.dialog > .body > .header{
				padding: 3px;
				min-height: 20px;
				vertical-align: middle;
				background-color: #f0f0f0;
				border: 1px solid #aaa;
				font-size: 14px;
			}
			.dialog > .body > .footer{
				position: absolute;
				bottom: 0;
				left: 0;
				right: 0;
				min-height: 30px;
				max-height: 30px;
				text-align: right;
				padding: 5px;
				vertical-align: middle;
				border: 1px solid #aaa;
			}
			.dialog > .body > .footer > .actions {
				vertical-align: middle;
				text-align: right;
			}
			.dialog > .body > .contents > .main{
				max-height: 400px;
				overflow: auto;
				margin-bottom: 20px;
			}
			.dialog > .body > .contents > .toolbar{
				height: 20px;
				padding: 5px;
				vertical-align: middle;
			}
			.dialog > .body > .contents > .toolbar *{
				vertical-align: middle;	
				display: inline-block;
			}
			.hidden{
				display: none;
			}
			.actions.actioncell .sending{
				display: none;
			}
			.actions.actioncell .unselect{
				display: none;
			}
			table.treetable tr.selectedtopic > td{
				background-color: #DEFFA3;
			}
			table.treetable tr.selectedtopic button.select{
				display: none;
			}
			table.treetable tr.selectedtopic button.unselect{
				display: inline-block;
			}
			table.treetable.updating tr td button,
			table.treetable.updating tr.selectedtopic td button,
			table.treetable.updating tr:hover td .actions button,
			table.treetable.updating tr td.updating button{
				display: none;
			}
			table.treetable.updating tr td.updating .sending {
				display: inline-block;
				padding: 5px;
				margin: 2px;
				background-color: #5C8DCA;
				border: 1px solid #5C8DCA;
				border-radius: 2px;
				color: white;
			}
			table.viewselected tbody tr{
				display: none !important;
			}
			table.viewselected tbody tr.hasvalue,
			table.viewselected tbody tr.selectedchildren,
			table.viewselected tbody tr.haschildren{
				display: table-row !important;
			}
			table.treetable tr.selectedchildren.branch > td {
				background-color: #EEEED1;
			}
			table.treetable tr td.reportcell .topics.local.hasvalue{
				display: none;
			}
			table.treetable thead tr th{
				padding: 5px 3px;
			}
			table.treetable tbody tr td.reportcell,
			table.treetable tbody tr td.usagecell,
			table.treetable thead tr th.usage{
				max-width: 35px;
				padding: 5px 3px;
				width: 35px;
				margin: 0;
			}
			table.treetable tbody tr td.usagecell{
				border-right: 1px solid #DADADA;
			}
			
			table.treetable > tbody > tr > td.reportcell,
			table.treetable > thead > tr > th.report{
				display:none;
			}
			table.treetable > tbody > tr > td.usagecell,
			table.treetable > thead > tr > th.usage {
				display: none;
			}
			table.treetable.viewusage > tbody > tr > td.usagecell,
			table.treetable.viewusage > thead > tr > th.usage {
				display: table-cell;
			}
			.mapper .toolbar .filter > div {
				display: inline-block;
				padding: 2px 5px;
				vertical-align: middle;
			}
			.mapper .toolbar .filter > div > *{
				vertical-align: middle;
			}
			
			.emptymessage{
				display: none;
				margin: 0 auto;
				padding: 10px 0px;
				text-align: center;
			}
			.emptymessage > span {
				text-align: center;
				vertical-align: middle;
				border: 1px solid #E0E0E0;
				background-color: #F0F0F0;
				padding: 10px 25px;
				border-radius: 2px;
			}
			
			.isempty.viewselected .emptymessage{
				display: block;
			}
			.treecontainer {
				min-height: 300px;
			}
		</style>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.3.1/lodash.min.js" ></script>
		<script src="https://code.jquery.com/jquery-2.1.3.min.js" type="text/javascript"></script>
		<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js" type="text/javascript"></script>
		
		<script src="/elixir/ludo-jquery-treetable/jquery.treetable.js" type="text/javascript"></script>
		<script type="text/javascript">
			// Figure out what browser is being used
			$.browser = {};
			var appdb = appdb || {};
			var elixir = elixir || {};
			elixir.config = {
				"host": '<?php echo $_SERVER["SERVER_NAME"]; ?>'
			};
		</script>
		<script type="text/javascript" src="/js/appdb.config.js.php"></script>
		<script type="text/javascript" src="/js/appdb.utils.js"></script>
		<script type="text/javascript" src="/elixir/elixir.js"></script>
		<script type="text/javascript" src="/elixir/elixir.data.js"></script>
		<script type="text/javascript" src="/elixir/elixir.view.js"></script>
	</head>
	<body>
		<h1>Mapping Elixir topics to AppDB disciplines</h1>
		<div class='loader'>loading....</div>
		<div class="toolbar hidden">
			<button type="button" class="view-selector" data-view="disciplines">Per Discipline</button>
			<button type="button" class="view-selector" data-view="topics">Per Topics</button>
		</div>
		<div class="mapper view-disciplines">
			<div class="toolbar">
				<div class="filter">
					<div class="filter-selected-disciplines">
						<input type="checkbox" name="viewselecteddisciplines"/><label for="viewselecteddisciplines">view only selected</label>
					</div>
					<div class="filter-discipline-usage">
						<input type="checkbox" name="viewdisciplineusage"/><label for="viewdisciplineusage">view usage</label>
					</div>
					<div class="collapse-all" style="float: right;padding: 3px;">
						<a href="#" onclick="$('.disciplinesview > table').treetable('expandAll');return false;" title="click to expand all nodes">expand all</a> 
						<a href="#" onclick="$('.disciplinesview > table').treetable('collapseAll');return false;" title="click to collapse all nodes">collapse all</a> 
					</div>
				</div>
			</div>
			<div class="treecontainer disciplinesview"><div class="emptymessage"><span>No selected items</span></div></div>
			<div class="treecontainer topicsview hidden"></div>
		</div>
		<script type="text/javascript">
			function elixirDataLoaded(d){
				//console.log(d.disciplines); 
				//console.log(d.edam); 
				$(".loader").addClass("hidden");
				elixir.view.renderDisciplines($(".mapper > .treecontainer.disciplinesview"));
				elixir.view.renderTopics($(".mapper > .treecontainer.topicsview"));
			}
			elixir.data.on("dataloaded", elixirDataLoaded);
			$(document).ready(function(){
				$(".toolbar button.view-selector").unbind("click").bind("click", function(ev){
					ev.preventDefault();
					$(".mapper").removeClass().addClass("mapper").addClass("view-" + $(this).data("view"));
					return false;
				});
				elixir.data.loadData();
				$("body").bind("keyup", function(ev){
					if (ev.keyCode == 27){
						$("body").removeClass("showdialog");
					}
				});
			});			
		</script>
		<div class='dialog'>
			<div class='shader'></div>
			<div class='body'>
				<div class='header'><div class='title'></div></div>
				<div class='contents'>
					<div class="toolbar">
						<div class="filter">
							<input type="checkbox" name="onlyselected"/><label for="onlyselected">selected only</label>
						</div>
						<div class="collapse-all" style="float: right;padding: 3px;">
							<a href="#" onclick="$('.dialog > .body table.treetable').treetable('expandAll');return false;" title="click to expand all nodes">expand all</a> 
							<a href="#" onclick="$('.dialog > .body table.treetable').treetable('collapseAll');return false;" title="click to collapse all nodes">collapse all</a> 
						</div>
					</div>
					<div class="main">
						<div class='treecontainer topicsview topicsContainer'><div class="emptymessage"><span>No selected items</span></div></div>						
					</div>
				</div>
				<div class='footer'><div class='actions'><button type='button' class='close'>close</button></div></div>
			</div>
		</div>
	</body>
</html>

