    <?php if ( ( $_SERVER['HTTP_HOST'] == "appdb.egi.eu" ) || ( $_SERVER['HTTP_HOST'] == "appdb-dev.marie.hellasgrid.gr" ) ) { ?>
    <script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
    try {
        <?php if ( $_SERVER['HTTP_HOST'] == "appdb.egi.eu" ) { ?>
       var pageTracker = _gat._getTracker("UA-1281621-4");
       pageTracker._trackPageview();
       var secondTracker = _gat._getTracker("UA-19331427-1");
       secondTracker._trackPageview();
       <?php } ?>
       <?php if ( $_SERVER['HTTP_HOST'] == "appdb-dev.marie.hellasgrid.gr" ) { ?>
       var pageTracker = _gat._getTracker("UA-19331427-2");
       pageTracker._trackPageview();
       <?php } ?>
    } catch(err){}
    </script>
    <?php } ?>

