<?php
class Repository_Model_DbTable_Row_CommRepoAllowedOsDmethodCombinations extends Zend_Db_Table_Row_Abstract
{


}

class Repository_Model_DbTable_CommRepoAllowedOsDmethodCombinations extends Repository_Model_DbTable_CommRepoAllowedOsDmethodCombinationsBase
{
	protected $_rowClass = 'Repository_Model_DbTable_Row_CommRepoAllowedOsDmethodCombinations';
}
