<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Repository_Model_DbTable_CommRepoRepositoriesBase extends Repository_Model_DbTable_ZendDBTable
{
	protected $_name = 'comm_repo_repositories';
	protected $_primary = 'id';
	protected $_sequence = true;
}
