<?php
class Repository_Model_DbTable_Row_CommRepoAllowedPlatformCombinations extends Zend_Db_Table_Row_Abstract
{


}

class Repository_Model_DbTable_CommRepoAllowedPlatformCombinations extends Repository_Model_DbTable_CommRepoAllowedPlatformCombinationsBase
{
	protected $_rowClass = 'Repository_Model_DbTable_Row_CommRepoAllowedPlatformCombinations';
}
