<?php
class Repository_Model_DbTable_Row_DeletedMetaPoaReleasePackages extends Zend_Db_Table_Row_Abstract
{


}

class Repository_Model_DbTable_DeletedMetaPoaReleasePackages extends Repository_Model_DbTable_DeletedMetaPoaReleasePackagesBase
{
	protected $_rowClass = 'Repository_Model_DbTable_Row_DeletedMetaPoaReleasePackages';
}
