<?php
class Repository_Model_DbTable_Row_DeletedMetaProductRepoArea extends Zend_Db_Table_Row_Abstract
{


}

class Repository_Model_DbTable_DeletedMetaProductRepoArea extends Repository_Model_DbTable_DeletedMetaProductRepoAreaBase
{
	protected $_rowClass = 'Repository_Model_DbTable_Row_DeletedMetaProductRepoArea';
}
