<?php
class Repository_Model_DbTable_Row_DeletedMetaProductRepoAreas extends Zend_Db_Table_Row_Abstract
{


}

class Repository_Model_DbTable_DeletedMetaProductRepoAreas extends Repository_Model_DbTable_DeletedMetaProductRepoAreasBase
{
	protected $_rowClass = 'Repository_Model_DbTable_Row_DeletedMetaProductRepoAreas';
}
