<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Repository_Model_DbTable_DeletedMetaPoaReleaseBase extends Zend_Db_Table_Abstract
{
	protected $_name = 'deleted_meta_poa_release';
	protected $_primary = 'id';
	protected $_sequence = false;
}
