<?php
class Repository_Model_DbTable_Row_MetaProductReleaseKeywords extends Zend_Db_Table_Row_Abstract
{


}

class Repository_Model_DbTable_MetaProductReleaseKeywords extends Repository_Model_DbTable_MetaProductReleaseKeywordsBase
{
	protected $_rowClass = 'Repository_Model_DbTable_Row_MetaProductReleaseKeywords';
}
