<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
require_once('ZendDBTableBase.php');
class Repository_Model_DbTable_MetaContactsBase extends Repository_Model_DbTable_ZendDBTable
{
	protected $_name = 'meta_contacts';
	protected $_primary = 'id';
	protected $_sequence = true;
}
