<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Repository_Model_DbTable_MetaProductCapabilitiesBase extends Repository_Model_DbTable_ZendDBTable
{
	protected $_name = 'meta_product_capabilities';
	protected $_primary = 'id';
	protected $_sequence = true;
}
