<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN

class Repository_Model_DbTable_VMetaProductRepoAreaContactsBase extends Repository_Model_DbTable_ZendDBTable
{
	protected $_name = 'v_meta_product_repo_area_contacts';
	protected $_primary = '';
	protected $_sequence = false;
}
