<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
class Default_Model_VaProvidersMapperBase
{
	protected $_dbTable;

	private function pgBool($v) { if ($v) return 't'; else return 'f'; }

	public function setDbTable($dbTable)
	{
		if (is_string($dbTable)) {
			$dbTable = new $dbTable();
		}
		if (!$dbTable instanceof Zend_Db_Table_Abstract) {
			throw new Exception('Invalid table data gateway provided');
		}
			$this->_dbTable = $dbTable;
			return $this;
	}

	public function getDbTable()
	{
		if (null === $this->_dbTable) {
			$this->setDbTable('Default_Model_DbTable_VaProviders');
		}
		return $this->_dbTable;
	}

	public function save(Default_Model_VaProvider $value)
	{
		global $application;
		$data = array();
		if ( ! isnull($value->getId()) ) $data['id'] = $value->getId();
		if ( ! isnull($value->getSitename()) ) $data['sitename'] = $value->getSitename();
		if ( ! isnull($value->getUrl()) ) $data['url'] = $value->getUrl();
		if ( ! isnull($value->getGocdbUrl()) ) $data['gocdb_url'] = $value->getGocdbUrl();
		if ( ! isnull($value->getHostname()) ) $data['hostname'] = $value->getHostname();
		if ( ! isnull($value->getServiceID()) ) $data['serviceid'] = $value->getServiceID();
		if ( ! isnull($value->getHostDn()) ) $data['host_dn'] = $value->getHostDn();
		if ( ! isnull($value->getHostIp()) ) $data['host_ip'] = $value->getHostIp();
		if ( ! isnull($value->getHostOsId()) ) $data['host_os_id'] = $value->getHostOsId();
		if ( ! isnull($value->getHostArchId()) ) $data['host_arch_id'] = $value->getHostArchId();
		if ( ! isnull($value->getBeta()) ) $data['beta'] = $this->pgBool($value->getBeta());
		if ( ! isnull($value->getInProduction()) ) $data['in_production'] = $this->pgBool($value->getInProduction());
		if ( ! isnull($value->getNodeMonitored()) ) $data['node_monitored'] = $this->pgBool($value->getNodeMonitored());
		if ( ! isnull($value->getCountryId()) ) $data['country_id'] = $value->getCountryId();
		if ( ! isnull($value->getNgi()) ) $data['ngi'] = $value->getNgi();
		if ( ! isnull($value->getGuID()) ) $data['guid'] = $value->getGuID();


		$q1 = '';
		$q2 = '';
		if (null === ($id = '')) {
			unset($data['']);
			$this->getDbTable()->insert($data);
		} else {
			$s = $this->getDbTable()->getAdapter()->quoteInto($q1,$q2);
			$this->getDbTable()->update($data, $s);
		}
	}

	public function delete(Default_Model_VaProvider $value)
	{
		$q1 = '';
		$q2 = '';
		$s=$this->getDbTable()->getAdapter()->quoteInto($q1,$q2);
		$this->getDbTable()->delete($s);
	}

	public function populate(&$entry,$row)
	{
		$entry->setId($row->id);
		$entry->setSitename($row->sitename);
		$entry->setUrl($row->url);
		$entry->setGocdbUrl($row->gocdb_url);
		$entry->setHostname($row->hostname);
		$entry->setServiceID($row->serviceid);
		$entry->setHostDn($row->host_dn);
		$entry->setHostIp($row->host_ip);
		$entry->setHostOsId($row->host_os_id);
		$entry->setHostArchId($row->host_arch_id);
		$entry->setBeta($row->beta);
		$entry->setInProduction($row->in_production);
		$entry->setNodeMonitored($row->node_monitored);
		$entry->setCountryId($row->country_id);
		$entry->setNgi($row->ngi);
		$entry->setGuID($row->guid);
	}

	public function find($id, Default_Model_VaProviders &$value)
	{
		$result = $this->getDbTable()->find($id);
		if (0 == count($result)) {
			return;
		}		$row = $result->current();
		$this->populate($value,$row);	}

	public function count($filter = null)
	{
		$select = $this->getDbTable()->select();
		$select->from($this->getDbTable(),array('COUNT(*) AS count'));
		if ( ($filter !== null) && ($filter->expr() != '') ) {
			$select->where($filter->expr());
		}
		$res = $this->getDbTable()->fetchAll($select);
		return $res[0]->count;
	}
	public function fetchAll($filter = null, $format = '')
	{
		$select = $this->getDbTable()->select();
		if ( ($filter !== null) && ($filter->expr() != '') ) {
			$select->where($filter->expr());
		}
		if ($filter !== null) $select->limit($filter->limit, $filter->offset);
		if ($filter !== null) $select->order($filter->orderBy);
		$resultSet = $this->getDbTable()->fetchAll($select);
		$entries = array();
		foreach ($resultSet as $row) {
			$entry = new Default_Model_VaProvider();
			$this->populate($entry,$row);
			if ($format === 'xml') $entry = $entry->toXML(true);
			$entries[] = $entry;
		}		return $entries;
	}
}
