<br /><br />
<style>
  .modal {
    display: block;
    max-width: 580px;
    min-width: 580px;
    margin: 0 auto;
  }

  .modal > .header {
    font-size: 1.3em;
    line-height: 1.2857em;
    font-weight: 700;
    display: block;
    font-family: Arial,Helvetica,sans-serif;
    background: #FFF;
    margin: 0;
    padding: 1rem 1.5rem;
    box-shadow: none;
    color: rgba(0,0,0,.85);
    border-bottom: 1px solid rgba(34,36,38,.15);
  }
  
  .modal > * {
    padding: 10px;
  }

  .modal > .content {
    padding: 0.5em 1.5em;
  }
  .modal > .content.error {
    border: 1px solid #ddd;
    background: lightgoldenrodyellow;
  }
  
  .modal > .content .centered {
    margin: 0 auto;
    display: block;
  }
  .modal > .content > p {
      margin: 5px;
  }
  .modal > .actions {
    text-align: center;
    padding: 0.5em 1.5em;
  }
  .modal > .actions > .redirection {
      display: none;
  }
  .modal > .actions.redirecting > a {
      display: none;
  }
  
  .modal > .actions.redirecting > .redirection {
      display: block;
      width: 300px;
      height: 40px;
      text-align: center;
      margin: 0 auto;
      background-color: #ddd;
      color: #333;
      line-height: 40px;
      border-radius: 5px;
  }

  .button {
    cursor: pointer;
    display: inline-block;
    min-height: 1em;
    outline: 0;
    border: none;
    vertical-align: baseline;
    background: #E0E1E2;
    color: rgba(0,0,0,.6);
    font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
    margin: 0 .25em 0 0;
    padding: .78571429em 1.5em;
    text-transform: none;
    text-shadow: none;
    font-weight: 700;
    line-height: 1em;
    font-style: normal;
    text-align: center;
    text-decoration: none;
    border-radius: .28571429rem;
    box-shadow: 0 0 0 1px transparent inset, 0 0 0 0 rgba(34,36,38,.15) inset;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  .button.positive {
    background-color: green;
    color: white;
  }
  .button.positive:hover {
    background-color: #16ab39;
    color: #FFF;
    text-shadow: none;
  }
  .button.negative {
    background-color: #DB2828;
    color: #FFF;
    text-shadow: none;
    background-image: none;
  }
  .button.negative:hover {
    background-color: #d01919;
    color: #FFF;
    text-shadow: none;
  }
  .error_status,
  .error_description {
    color: #555;      
  }
  .error_status > b,
  .error_description > b {
    color: #666;
  }
  ul {
      list-style: none;
      margin: 10px;
      padding: 0;
  }
  ul > li {
      padding: 15px;
      border: 1px solid #c0c0c0;
      background-color: #fdfdfd;
      border-radius: 2px;
      margin: 5px;
  }
  h4 {
      color: #555;
  }
  img.service-logo {
      width: 20px;
      height: 20px;
  }
  
  .error.content {
      color: #555;
  }
  .error.content > p {
      display: block;
      margin: 5px;
  }
</style>
<script type="text/javascript">
    function onOIDCAuthorizeButtonClick(ev) {
        debugger;
        $(ev).css('background-color', '#aaa').text('Redirecting to EGI AAI');
    }
</script>
<div id="view-content" class="modal" style="font-family:Arial">
        <?php if ($this->serviceName) { ?>
        <div class="header">
            <?php if ($this->serviceLogo) { ?>
            <img src="<?php echo $this->serviceLogo; ?>" class="service-logo"></img>
            <?php } ?>
            <span class="service-name"><?php echo $this->serviceName; ?></span>
            needs authorization
        </div>
        <?php } else { ?>
        <div class="header">
            <span class="service-name">EGI AppDB OpenID connect</span>
        </div>
        <?php } ?>
        <?php if($this->isAuthenticated === true) { ?>
            <?php if(trim($this->error)){ ?>
                <div class="content error" >
                    <p style="margin: 0; margin-bottom:10px;"><b style="color: red; font-size:20px; margin:0 5px;">!</b><b>An error occurred</b></p>
                    <p class="error_status"><b>code: </b><?php echo htmlspecialchars($this->error, ENT_QUOTES, "UTF-8"); ?></p>
                    <p class="error_description"><b>description: </b><?php echo htmlspecialchars($this->errorDescription, "UTF-8"); ?></p>
                    <?php if ($this->errorDetails) { ?>
                    <p class="error_details"><b>details: </b><pre><?php echo $this->errorDetails; ?></pre></p>
                    <?php } ?>
		</div>
		<div class="actions">
                    <a class="button negative" href="javascript:window.close()">Close</a>
                </div>
            <?php } else { ?>
		<div class="content">
                    <p>This service requires the following permissions to be granted:</p>
                    <ul class="list-group list-group-flush">
                        <?php foreach($this->scopesDescription as $scope => $scopeDescription){ ?>
                        <li class="list-group-item"><?php echo $scopeDescription; ?></li>
                        <?php } ?>
                    </ul>
                    <p>If you do not consent click the <i>cancel</i> button.</p>
                </div>
                <div class="actions">
                    <a class="button positive" href="<?php echo $this->refreshTokenUrl; ?>" onClick="document.querySelector && document.querySelector('.actions').classList.add('redirecting')">Authorize</a>
                    <a class="button negative" href="javascript:window.close()">Cancel</a>
                    <div class="redirection">Redirecting to EGI AAI Check-in...</div>
                </div>
            <?php } ?>
        <?php } else { ?>
            <div class="error content">
              <p>In order to continue you need to be authenticated as a valid user. </p><p>Please login to the EGI AppDB first.</p>
            </div>
            <div class="actions">
              <a class="button negative" href="javascript:window.close()">Close</a>
            </div>
        <?php } ?>
</div>
