<br /><br />
<style>
  .modal {
    display: block;
    max-width: 580px;
    min-width: 580px;
    margin: 0 auto;
  }

  .modal > .header {
    font-size: 1.3em;
    line-height: 1.2857em;
    font-weight: 700;
    display: block;
    font-family: Arial,Helvetica,sans-serif;
    background: #FFF;
    margin: 0;
    padding: 1.25rem 1.5rem;
    box-shadow: none;
    color: rgba(0,0,0,.85);
    border-bottom: 1px solid rgba(34,36,38,.15);
  }
  
  .modal > * {
    padding: 10px;
  }

  .modal > .content {
    padding: 1.25em 1.5em;
  }
  .modal > .content.error {
    border: 1px solid #ddd;
    background: lightgoldenrodyellow;
  }
  
  .modal > .content .centered {
    margin: 0 auto;
    display: block;
  }
  
  .modal > .actions {
    text-align: center;
  }

  .button {
    cursor: pointer;
    display: inline-block;
    min-height: 1em;
    outline: 0;
    border: none;
    vertical-align: baseline;
    background: #E0E1E2;
    color: rgba(0,0,0,.6);
    font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
    margin: 0 .25em 0 0;
    padding: .78571429em 1.5em;
    text-transform: none;
    text-shadow: none;
    font-weight: 700;
    line-height: 1em;
    font-style: normal;
    text-align: center;
    text-decoration: none;
    border-radius: .28571429rem;
    box-shadow: 0 0 0 1px transparent inset, 0 0 0 0 rgba(34,36,38,.15) inset;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  .button.positive {
    background-color: green;
    color: white;
  }
  .button.positive:hover {
    background-color: #16ab39;
    color: #FFF;
    text-shadow: none;
  }
  .button.negative {
    background-color: #DB2828;
    color: #FFF;
    text-shadow: none;
    background-image: none;
  }
  .button.negative:hover {
    background-color: #d01919;
    color: #FFF;
    text-shadow: none;
  }
  .error_status {
    font-weight: bold;
  }
  
  pre {
    margin: 0;
    padding: 0;
    display: block;
    max-width: 550px;
    overflow: hidden;
    white-space: pre-wrap;
    word-break: break-all;
    padding: 10px;
    margin-top: 5px;
    border: 1px solid #dadada;
    border-radius: 4px;
    background-color: #fdfdfd;
    box-shadow: 1px 1px 8px 1px #ececec inset;
    font-size: 12px;
    font-weight: normal;
  }
  img.service-logo {
      width: 20px;
      height: 20px;
  }
</style>
<div id="view-content" class="modal" style="font-family:Arial">
   <?php if($this->isAuthenticated === true) {
           if(isset($this->error)){ ?>
                <div class="header">An error occurred</div>
                <div class="content error" >
                  <div class="error_status"><?php echo htmlspecialchars($this->error, ENT_QUOTES, "UTF-8"); ?></div>
                  <div class="error_description"><?php echo htmlspecialchars($this->error_description, ENT_QUOTES, "UTF-8"); ?></div>
                </div>
                <div class="actions">
                  <a class="button negative" href="javascript:window.close()">Close</a>
                </div>
	  <?php } else if($this->accessToken) { ?>
                <div class="header">Success for
                    <?php if ($this->serviceLogo) { ?><img src="<?php echo $this->serviceLogo; ?>" class="service-logo" /><?php } ?>
                    <span class="service-name"><?php echo $this->serviceName; ?></span>
                </div>
                <div class="content">You have successfully obtained a new access token. You may close this window and proceed with the action.</div>
                <br/>
                <div>Access Token: <pre><?php echo $this->accessToken; ?></pre></div>
                <div class="actions">
                  <a class="button negative" href="javascript:window.close()">Close</a>
                </div>
          <?php } else { ?>
                <div class="header">No access token</div>
                <div class="content">No access token is created and error occurred.</div>
                <div class="actions">
                  <a class="button negative" href="javascript:window.close()">Close</a>
                </div>
          <?php } ?>
   <?php } else { ?>
        <div class="header">Not authenticated</div>
          <div class="content">
            <p>In order to obtain aN access token you need to be authenticated as a valid user. </p><p>Please login to the EGI AppDB first.</p>
	  </div>
	  <div class="actions">
            <a class="button negative" href="javascript:window.close()">Close</a>
          </div>
        </div>
   <?php } ?>


