<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><div id="maincontent" align="center" style="display:block;">
	<table id="tblmain" border="0" width="100%" id="table1" bgcolor="#FFFFFF" cellspacing="0">
		<tr bgcolor="white" height="70px">
		<td></td>
			<td width="230px" style="background-color:white; vertical-align: middle">
	  			<div align="left">
					<a target="_blank" href="http://egi.eu/">
						<img border="0" style="padding: 15 15 15 15;" src="/images/EGI-logo_small.png"/>
					</a>
	  			</div>
	  			<div style="position:absolute; left:145px; top:15px">
					<img border="0" src="/images/egi_moto.png"/>
	  			</div>
			</td>
			<td background="/images/header_back70.png">
				<div align="left"><h2>Applications Database</h2></div>
			</td>
			<td background="/images/header_back70b.png" width="2%"></td>
		</tr>
		<tr height="4"><td colspan="4" background="/images/bar1.png"></td></tr>
    </table>
    <div align="left" style="margin-left:20px">
    <h1 style="text-align:left">Unsupported Browser</h1>
    It appears that you are viewing this page with a Web browser that is not fully supported. This Web site works best with one of these supported browsers:

    <ul>
<?php readfile(APPLICATION_PATH.'/../public/browserlist.txt');?>
    </ul>

    while experimental support exists for:
    <ul>
        <li>Microsoft Internet Explorer 8.0</li>
    </ul>
    If you continue using this browser, some functionality may be hindered, or broken. Please use the <a target="_blank" href="http://helpdesk.egi.eu/">EGI Helpdesk</a> to report any problems you may encounter, and help us improve functionality.<p></p>
    <?php $this->session->msie8acknol=true; ?>
    <a href="/">Continue</a>
    </div>
</div>
<div id="footer">
	<table width="100%" cellspacing="0">
		<tr height="4"><td colspan="3" background="/images/bar1.png"></td></tr>
		<tr background="/images/header_back70b.png">
			<td width="10%" align="center">
			</td>
			<td align="center" style="text-align: center">
				<a style="text-decoration:none" href="http://www.iasa.gr/" target="_blank"><font color="#455058">&copy; Institute of Accelerating Systems and Applications</font></a>, 2009-<?php echo date("Y");?><br/>Athens, Greece
			</td>
			<td width="10%" align="right" style="text-align: right">
				<br/>v.<?php echo exec("cat ".APPLICATION_PATH."/../VERSION");?>
				<p/>
			</td>
		</tr>			
	</table>
</div>
