<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><div class="listcontainer software">
<table border="0"  id="apps_main_content" style="width:100%;height:100%;">
	<tr >
		<td style="width:100%;">
			<div class="listcontainer-header">
				<div class="simpleFilter">
					<span  id="apps_filter" style="white-space: nowrap; margin-left: 0; margin-right: auto"></span>
				</div>
				<div class="orderby">
					<div id="apps_orderby" style="white-space: nowrap; vertical-align: middle; "></div>
				</div>
				<div id="apps_viewbuttons" class="listtypebuttons" ></div><a href="#" id="alphaSwitch" class="pagingtype" style="display:none;" title="Click to enable alpha numeric paging" >ABC</a>
				<div id="apps_loading" class="loader">
					<img src="/images/ajax-loader-small.gif" alt="" width="12px" height="12px" />
					<span >Loading...</span>
				</div>
			</div>
		</td>
	</tr>
	<tr >
		<td align="center">
			<div class="refinedfiltering">
				<div id="apps_managedfilters" class="managedfilter" >
					<span class="title">Filters:</span>
					<ul></ul>
					<a href="#" title="Display available filters" class="action display"><span>refine your search</span><span class="collapsed">|&#x25BC;</span><span class="expanded">|&#x25B2;</span></a>
					<a href="#" title="Clear all filters" class="action reset hidden"><img src="/images/cancelicon.png" alt="" /><span>clear all</span></a>
				</div>
				<div id="apps_logisticsselector" class="logisticsselector" style="display: none"></div>
			</div>
			<div class="listmetadata">
				<div id="apps_result_time" ></div>
			</div>
			<div id='apps_paging' class="pager"></div>
			<div id="apps_alphapaging" style="width:100%;text-align: center;margin-left:0px;"></div>
		</td>
	</tr>
	<tr>
		<td>
			<ul className="itemgrid" class="itemgrid" id="appmainlist"></ul>
		</td>
	</tr>
	<tr>
		<td>
			<div id='apps_paging_bottom' class="pager"></div>
		</td>
	</tr>
</table>
<ul class="listtoolbox">
	<li><div id="apps_atomfeed" ></div><div class="description">RSS</div></li>
    <li><div id="apps_mailfeed"></div><div class="description">MAIL</div></li>
    <li><div id="apps_permalink"></div><div class="description">PERMALINK</div></li>
	<li><div id="exportdiv" ></div><div class="description last">EXPORT</div></li>
</ul>
</div>
