<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
class Repository_Model_DeletedMetaProductRepoAreasMapperBase
{
	protected $_dbTable;

	private function myBool($v) { if ($v) return 1; else return 0; }

	public function setDbTable($dbTable)
	{
		if (is_string($dbTable)) {
			$dbTable = new $dbTable();
		}
		if (!$dbTable instanceof Zend_Db_Table_Abstract) {
			throw new Exception('Invalid table data gateway provided');
		}
			$this->_dbTable = $dbTable;
			return $this;
	}

	public function getDbTable()
	{
		if (null === $this->_dbTable) {
			$this->setDbTable('Repository_Model_DbTable_DeletedMetaProductRepoAreas');
		}
		return $this->_dbTable;
	}

	public function save(Repository_Model_DeletedMetaProductRepoArea $value)
	{
		global $application;
		$data = array();
		if ( ! isnull($value->getDeletedBy()) ) $data['deletedBy'] = $value->getDeletedBy();
		if ( ! isnull($value->getTimestampDeleted()) ) $data['timestampDeleted'] = $value->getTimestampDeleted();
		if ( ! isnull($value->getId()) ) $data['id'] = $value->getId();
		if ( ! isnull($value->getName()) ) $data['name'] = $value->getName();
		if ( ! isnull($value->getSwId()) ) $data['swId'] = $value->getSwId();
		if ( ! isnull($value->getSwName()) ) $data['swName'] = $value->getSwName();
		if ( ! isnull($value->getDescription()) ) $data['description'] = $value->getDescription();
		if ( ! isnull($value->getInstallationNotes()) ) $data['installationNotes'] = $value->getInstallationNotes();
		if ( ! isnull($value->getAdditionalDetails()) ) $data['additionalDetails'] = $value->getAdditionalDetails();
		if ( ! isnull($value->getYumRepofileId()) ) $data['yumRepofileId'] = $value->getYumRepofileId();
		if ( ! isnull($value->getAptRepofileId()) ) $data['aptRepofileId'] = $value->getAptRepofileId();
		if ( ! isnull($value->getKnownIssues()) ) $data['knownIssues'] = $value->getKnownIssues();
		if ( ! isnull($value->getTimestampInserted()) ) $data['timestampInserted'] = $value->getTimestampInserted();
		if ( ! isnull($value->getTimestampLastUpdated()) ) $data['timestampLastUpdated'] = $value->getTimestampLastUpdated();
		if ( ! isnull($value->getTimestampLastProductionBuild()) ) $data['timestampLastProductionBuild'] = $value->getTimestampLastProductionBuild();
		if ( ! isnull($value->getInsertedBy()) ) $data['insertedBy'] = $value->getInsertedBy();


		$q1 = 'id = ?';
		$q2 = $value->id;
		if (null === ($id = $value->id)) {
			unset($data['id']);
			$value->id = $this->getDbTable()->insert($data);
		} else {
			$s = $this->getDbTable()->getAdapter()->quoteInto($q1,$q2);
			$this->getDbTable()->update($data, $s);
		}
	}

	public function delete(Repository_Model_DeletedMetaProductRepoArea $value)
	{
		$q1 = 'id = ?';
		$q2 = $value->id;
		$s=$this->getDbTable()->getAdapter()->quoteInto($q1,$q2);
		$this->getDbTable()->delete($s);
	}

	public function populate(&$entry,$row)
	{
		$entry->setDeletedBy($row->deletedBy);
		$entry->setTimestampDeleted($row->timestampDeleted);
		$entry->setId($row->id);
		$entry->setName($row->name);
		$entry->setSwId($row->swId);
		$entry->setSwName($row->swName);
		$entry->setDescription($row->description);
		$entry->setInstallationNotes($row->installationNotes);
		$entry->setAdditionalDetails($row->additionalDetails);
		$entry->setYumRepofileId($row->yumRepofileId);
		$entry->setAptRepofileId($row->aptRepofileId);
		$entry->setKnownIssues($row->knownIssues);
		$entry->setTimestampInserted($row->timestampInserted);
		$entry->setTimestampLastUpdated($row->timestampLastUpdated);
		$entry->setTimestampLastProductionBuild($row->timestampLastProductionBuild);
		$entry->setInsertedBy($row->insertedBy);
	}

	public function find($id, Repository_Model_DeletedMetaProductRepoAreas &$value)
	{
		$result = $this->getDbTable()->find($id);
		if (0 == count($result)) {
			return;
		}		$row = $result->current();
		$this->populate($value,$row);	}

	public function count($filter = null)
	{
		$select = $this->getDbTable()->select();
		$select->from($this->getDbTable(),array('COUNT(DISTINCT (id)) AS count'));
		if ( ($filter !== null) && ($filter->expr() != '') ) {
			$select->where($filter->expr());
		}
		$res = $this->getDbTable()->fetchAll($select);
		return $res[0]->count;
	}
	public function fetchAll($filter = null, $format = '')
	{
		$select = $this->getDbTable()->select();
		if ( ($filter !== null) && ($filter->expr() != '') ) {
			$select->where($filter->expr());
		}
		if ($filter !== null) $select->limit($filter->limit, $filter->offset);
		if ($filter !== null) $select->order($filter->orderBy);
		$resultSet = $this->getDbTable()->fetchAll($select);
		$entries = array();
		foreach ($resultSet as $row) {
			$entry = new Repository_Model_DeletedMetaProductRepoArea();
			$this->populate($entry,$row);
			if ($format === 'xml') $entry = $entry->toXML(true);
			$entries[] = $entry;
		}		return $entries;
	}
}