<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class AppDocumentBase extends AROItem {
	public function __construct() {
		$this->_basename = 'AppDocuments';
		$this->_baseitemname = 'AppDocument';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appid', 'appID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appid', 'application', 'Application');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'title', 'title');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'url', 'url');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'conference', 'conference');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'proceedings', 'proceedings');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'isbn', 'isbn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'pagestart', 'pageStart');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'pageend', 'pageEnd');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'volume', 'volume');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'publisher', 'publisher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'year', 'year');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'mainauthor', 'mainAuthor');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'doctypeid', 'docTypeID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'doctypeid', 'docType', 'DocType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'journal', 'journal');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guID');
	}
}
?>