<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATOCALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class AppTeamMapperBase
{
	protected $_dbTable;

	private function pgBool($v) { if ($v) return 't'; else return 'f'; }

	public function setDbTable($dbTable)
	{
		if (is_string($dbTable)) {
			$dbTable = new $dbTable();
		}
		if (!$dbTable instanceof Zend_Db_Table_Abstract) {
			throw new Exception('Invalid table data gateway provided');
		}
			$this->_dbTable = $dbTable;
			return $this;
	}

	public function getDbTable()
	{
		if (null === $this->_dbTable) {
			$this->setDbTable('DbTable\AppTeam');
		}
		return $this->_dbTable;
	}

	public function save(AROItem $value)
	{
		$data = array();
		if ( ! isnull($value->getAppID()) ) $data['appid'] = $value->getAppID();
		if ( ! isnull($value->getId()) ) $data['id'] = $value->getId();
		if ( ! isnull($value->getFirstName()) ) $data['firstname'] = $value->getFirstName();
		if ( ! isnull($value->getLastName()) ) $data['lastname'] = $value->getLastName();
		if ( ! isnull($value->getDateInclusion()) ) $data['dateinclusion'] = $value->getDateInclusion();
		if ( ! isnull($value->getInstitution()) ) $data['institution'] = $value->getInstitution();
		if ( ! isnull($value->getCountryID()) ) $data['countryid'] = $value->getCountryID();
		if ( ! isnull($value->getPositionTypeID()) ) $data['positiontypeid'] = $value->getPositionTypeID();


		$q1 = '';
		$q2 = '';
		if (null === ($id = '')) {
			unset($data['']);
			$this->getDbTable()->insert($data);
		} else {
			$s = $this->getDbTable()->getAdapter()->quoteInto($q1,$q2);
			$this->getDbTable()->update($data, $s);
		}
	}

	public function delete(AppTeam $value)
	{
		$q1 = '';
		$q2 = '';
		$s=$this->getDbTable()->getAdapter()->quoteInto($q1,$q2);
		$this->getDbTable()->delete($s);
	}

	public function populate(&$entry,$row)
	{
		$entry->setAppID($row->appid);
		$entry->setId($row->id);
		$entry->setFirstName($row->firstname);
		$entry->setLastName($row->lastname);
		$entry->setDateInclusion($row->dateinclusion);
		$entry->setInstitution($row->institution);
		$entry->setCountryID($row->countryid);
		$entry->setPositionTypeID($row->positiontypeid);
	}

	public function find($id, AppTeam &$value)
	{
		$result = $this->getDbTable()->find($id);
		if (0 == count($result)) {
			return;
		}		$row = $result->current();
		$this->populate($value,$row);	}

	public function count($filter = null)
	{
		$select = $this->getDbTable()->getSql()->select();
		$select->columns(array('COUNT(*) AS count'));
		if ( ($filter !== null) && ($filter->expr() != '') ) {
			$select->where($filter->expr());
		}
		$res = db()->query(SQL2STR($this, $select))->toArray();
		return $res[0]['count'];
	}
	public function fetchAll($filter = null, $format = '')
	{
		$select = $this->getDbTable()->getSql()->select();
		if ( ($filter !== null) && ($filter->expr() != '') ) {
			$select->where($filter->expr());
		}
		if (! is_null($filter)) {
			if (! is_null($filter->limit)) $select->limit($filter->limit);
			if (! is_null($filter->offset)) $select->offset($filter->offset);
			if (! is_null($filter->orderBy)) $select->order($filter->orderBy);
		}
		$resultSet = db()->query(SQL2STR($this, $select), array())->toArray();
		$entries = array();
		foreach ($resultSet as $row) {
			$entry = new AppTeam();
			$this->populate($entry,$row);
			if ($format === 'xml') $entry = $entry->toXML(true);
			$entries[] = $entry;
		}		return $entries;
	}
}
