<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class AppViewBase extends AROItem {
	public function __construct() {
		$this->_basename = 'AppViews';
		$this->_baseitemname = 'AppView';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'name', 'name');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'description', 'description');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'abstract', 'abstract');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'logo', 'logo');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'statusid', 'statusID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'statusid', 'status', 'Status');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'middlewareid', 'middlewareID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'middlewareid', 'middleware', 'Middleware');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'dateadded', 'dateAdded');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedBy');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'researcher', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'tool', 'tool');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'respect', 'respect');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'countryid', 'countryID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'countryid', 'country', 'Country');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'regionid', 'regionID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'regionid', 'region', 'Region');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'void', 'voID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'void', 'vo', 'VO');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'persondata', 'personData');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'hasdocs', 'hasDocs');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guid');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'deleted', 'deleted');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'moderated', 'moderated');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'categoryid', 'categoryID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'metatype', 'metatype');
	}
}
?>