<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class ContextScriptBase extends AROItem {
	public function __construct() {
		$this->_basename = 'ContextScripts';
		$this->_baseitemname = 'ContextScript';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'name', 'name');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'title', 'title');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'description', 'description');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'url', 'url');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'formatid', 'formatID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'formatid', 'contextFormat', 'ContextFormat');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'checksum', 'checksum');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'checksumfunc', 'checksumfunc');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'size', 'size');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedby', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedon', 'addedOn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastupdatedby', 'lastupdatedByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastupdatedby', 'lastupdatedByID', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastupdatedon', 'lastupdatedOn');
	}
}
?>