<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class DatasetLocationBase extends AROItem {
	public function __construct() {
		$this->_basename = 'DatasetLocations';
		$this->_baseitemname = 'DatasetLocation';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedBy', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedon', 'addedon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'uri', 'uri');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'is_master', 'isMaster');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'exchange_fmt', 'exchangeFormatID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'exchange_fmt', 'exchangeFormat', 'DatasetExchangeFormat');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'connection_type', 'connectionTypeID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'connection_type', 'connectionType', 'DatasetConnType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'is_public', 'isPublic');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'notes', 'notes');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'dataset_version_id', 'datasetVersionId');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'siteid', 'siteID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'organizationid', 'organizationID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'organizationid', 'organization', 'Organization');
	}
}
?>