<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class EntityRelationBase extends AROItem {
	public function __construct() {
		$this->_basename = 'EntityRelations';
		$this->_baseitemname = 'EntityRelation';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'reltypeid', 'relTypeID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'reltypeid', 'reltype', 'RelationType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'verbid', 'verbID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'verbid', 'verb', 'RelationVerb');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'target_guid', 'targetGuID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'target_type', 'targetType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'actionid', 'actionID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'actionid', 'action', 'Action');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'verb', 'verbName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'verbname', 'verbDName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'verbrname', 'verbRName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'subject_guid', 'subjectGuID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'subject_type', 'subjectType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'reltypeguid', 'reltypeguID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guid');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedon', 'addedon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedby');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'denyon', 'denyon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'denyby', 'denyby');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'hiddenon', 'hiddenon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'hiddenby', 'hiddenby');
	}
}
?>