<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class LinkStatusBase extends AROItem {
	public function __construct() {
		$this->_basename = 'LinkStatuses';
		$this->_baseitemname = 'LinkStatus';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appname', 'appName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ownerid', 'ownerID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ownerid', 'owner', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ownername', 'ownerName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'contact', 'contact');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'title', 'title');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'linkid', 'linkID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appid', 'appID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appid', 'application', 'Application');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'linktype', 'linkType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'urlname', 'urlName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'parentname', 'parentName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'baseref', 'baseRef');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'valid', 'valID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'result', 'result');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'warning', 'warning');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'info', 'info');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'url', 'url');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'line', 'line');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'col', 'col');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'name', 'name');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'checktime', 'checkTime');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'dltime', 'dlTime');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'dlsize', 'dlSize');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'cached', 'cached');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'firstchecked', 'firstChecked');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastchecked', 'lastChecked');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'age', 'age');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'whitelisted', 'whitelisted');
	}
}
?>