<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class RelationBase extends AROItem {
	public function __construct() {
		$this->_basename = 'Relations';
		$this->_baseitemname = 'Relation';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'reltypeid', 'relTypeID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'reltypeid', 'relationVerb', 'RelationType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'target_guid', 'targetGUID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'subject_guid', 'subjectGUID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'parentid', 'parentID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'parentid', 'parent', 'Relation');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedon', 'addedOn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedBy', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'denyon', 'denyOn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'denyby', 'denyByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'denyby', 'denyBy', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guid');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'hiddenon', 'hiddenOn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'hiddenby', 'hiddenByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'hiddenby', 'hiddenBy', 'Researcher');
	}
}
?>