<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class ResearcherBase extends AROItem {
	public function __construct() {
		$this->_basename = 'Researchers';
		$this->_baseitemname = 'Researcher';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'firstname', 'firstName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastname', 'lastName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'dateinclusion', 'dateInclusion');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'institution', 'institution');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'countryid', 'countryID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'countryid', 'country', 'Country');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'positiontypeid', 'positionTypeID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'positiontypeid', 'positionType', 'PositionType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guid');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastupdated', 'lastUpdated');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'name', 'name');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'mail_unsubscribe_pwd', 'mailUnsubscribePwd');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastlogin', 'lastLogin');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'nodissemination', 'noDissemination');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'accounttype', 'accountType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'deleted', 'deleted');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'hitcount', 'hitcount');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'cname', 'cname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedBy', 'Researcher');
	}
}
?>