<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class SiteBase extends AROItem {
	public function __construct() {
		$this->_basename = 'Sites';
		$this->_baseitemname = 'Site';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'name', 'name');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'shortname', 'shortname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'officialname', 'officialname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'description', 'description');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'portalurl', 'portalurl');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'homeurl', 'homeurl');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'contactemail', 'contactemail');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'contacttel', 'contacttel');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'alarmemail', 'alarmemail');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'csirtemail', 'csirtemail');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'giisurl', 'giisurl');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'countryid', 'countryID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'countryid', 'country', 'Country');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'countrycode', 'countrycode');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'countryname', 'countryname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'regionid', 'regionID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'regionid', 'region', 'Region');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'regionname', 'regionname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'tier', 'tier');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'subgrid', 'subgrID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'roc', 'roc');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'productioninfrastructure', 'productioninfrastructure');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'certificationstatus', 'certificationstatus');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'timezone', 'timezone');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'latitude', 'latitude');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'longitude', 'longitude');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'domainname', 'domainname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ip', 'ip');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'datasource', 'datasource');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'createdon', 'createdon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'createdby', 'createdby');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'updatedon', 'updatedon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'updatedby', 'updatedby');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'deleted', 'deleted');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'deletedon', 'deletedon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'deletedby', 'deletedby');
	}
}
?>