<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class UserRequestBase extends AROItem {
	public function __construct() {
		$this->_basename = 'UserRequests';
		$this->_baseitemname = 'UserRequest';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'typeid', 'typeID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'typeid', 'requestType', 'UserRequestType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'userguid', 'userGUID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'userdata', 'userData');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'targetguid', 'targetGUID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'actorguid', 'actorGUID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'actordata', 'actorData');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'stateid', 'stateID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'stateid', 'requestState', 'UserRequestState');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'created', 'created');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastupdated', 'lastUpdated');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guID');
	}
}
?>