<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class VaProviderBase extends AROItem {
	public function __construct() {
		$this->_basename = 'VaProviders';
		$this->_baseitemname = 'VaProvider';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'sitename', 'sitename');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'url', 'url');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'gocdb_url', 'gocdbUrl');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'hostname', 'hostname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'host_dn', 'hostDn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'host_ip', 'hostIp');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'host_os_id', 'hostOsId');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'host_arch_id', 'hostArchId');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'beta', 'beta');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'in_production', 'inProduction');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'node_monitored', 'nodeMonitored');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'country_id', 'countryId');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ngi', 'ngi');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'serviceid', 'serviceID');
	}
}
?>