<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class VAviewBase extends AROItem {
	public function __construct() {
		$this->_basename = 'VAviews';
		$this->_baseitemname = 'VAview';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vapplistid', 'vapplistID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vapplistid', 'vapplist', 'VAList');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vappversionid', 'vappversionID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vappversionid', 'vappversion', 'VAversion');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstanceid', 'vmiinstanceID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstanceid', 'vmiinstance', 'VMIinstance');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'size', 'size');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'uri', 'uri');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_version', 'vmiinstanceVersion');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'checksum', 'checksum');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'checksumfunc', 'checksumfunc');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_notes', 'vmiinstanceNotes');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_guid', 'vmiinstanceGUID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_addedon', 'vmiinstanceAddedon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_addedby', 'vmiinstanceAddedByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_addedby', 'vmiinstanceAddedBy', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiflavourid', 'vmiflavourID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiflavourid', 'vmiflavour', 'VMIflavour');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'autointegrity', 'autointegrity');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'coreminimum', 'coreminimum');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ramminimum', 'ramminimum');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_lastupdatedby', 'vmiinstanceLastupdatedByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_lastupdatedby', 'vmiinstanceLastupdatedBy', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_lastupdatedon', 'vmiinstanceLastupdatedon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_description', 'vmiinstanceDescription');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_title', 'vmiinstanceTitle');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'integrity_status', 'integrityStatus');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'integrity_message', 'integrityMessage');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ramrecommend', 'ramrecommend');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'corerecommend', 'corerecommend');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'accessinfo', 'accessinfo');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiinstance_enabled', 'vmiinstanceEnabled');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'initialsize', 'initialsize');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'initialchecksum', 'initialchecksum');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ovfurl', 'ovfurl');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiid', 'vmiID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiid', 'vmi', 'VMI');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'hypervisors', 'hypervisors');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'archid', 'archID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'archid', 'arch', 'Arch');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'osid', 'osID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'osid', 'os', 'OS');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'osversion', 'osversion');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'format', 'format');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmi_name', 'vmiName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmi_description', 'vmiDescription');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmi_guid', 'vmiGUID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_id', 'vaId');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_id', 'va', 'VA');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmi_notes', 'vmiNotes');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'groupname', 'groupname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_name', 'vaName');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appid', 'appID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appid', 'app', 'Application');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_guid', 'vaGUID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'imglst_private', 'imglstPrivate');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version', 'vaVersion');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_guid', 'vaVersionGUID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_notes', 'vaVersionNotes');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_published', 'vaVersionPublished');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_createdon', 'vaVersionCreatedon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_expireson', 'vaVersionExpireson');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_enabled', 'vaVersionEnabled');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_archived', 'vaVersionArchived');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_status', 'vaVersionStatus');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_archivedon', 'vaVersionArchivedon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'submissionid', 'submissionID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'submissionid', 'submission', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'va_version_isexternal', 'vaVersionIsexternal');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appname', 'appname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appcname', 'appcname');
	}
}
?>