<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class VMcasterRequestBase extends AROItem {
	public function __construct() {
		$this->_basename = 'VMcasterRequests';
		$this->_baseitemname = 'VMcasterRequest';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'status', 'status');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'username', 'username');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'password', 'password');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'authtype', 'authType');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'errormessage', 'errorMessage');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'insertedon', 'insertedOn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastsubmitted', 'lastSubmitted');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ip', 'ip');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'input_vmil', 'inputVMIL');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'produced_xml', 'producedXML');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appid', 'appID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'appid', 'application', 'Application');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'action', 'action');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'entity', 'entity');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ldap_sn', 'ldapSn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ldap_dn', 'ldapDn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ldap_email', 'ldapEmail');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ldap_displayname', 'ldapDisplayname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ldap_cn', 'ldapCn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ldap_usercertificatesubject', 'ldapUsercertificatesubject');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ldap_givenname', 'ldapGivenname');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'rid', 'rID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'uid', 'uID');
	}
}
?>