<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class VMIinstanceBase extends AROItem {
	public function __construct() {
		$this->_basename = 'VMIinstances';
		$this->_baseitemname = 'VMIinstance';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'size', 'size');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'uri', 'uri');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'version', 'version');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'checksum', 'checksum');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'checksumfunc', 'checksumFunc');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'notes', 'notes');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedon', 'addedOn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedbyID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'addedby', 'addedBy', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiflavourid', 'vmiflavourID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'vmiflavourid', 'flavour', 'VMIflavour');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'autointegrity', 'autoIntegrity');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'coreminimum', 'coreMinimum');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ramminimum', 'RAMminimum');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastupdatedby', 'lastUpdatedByID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastupdatedby', 'lastUpdatedBy', 'Researcher');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'lastupdatedon', 'lastUpdatedOn');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'description', 'description');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'title', 'title');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'integrity_status', 'integrityStatus');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'integrity_message', 'integrityMessage');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ramrecommend', 'RAMrecommend');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'corerecommend', 'coreRecommend');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'accessinfo', 'accessinfo');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'enabled', 'enabled');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'initialsize', 'initialsize');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'initialchecksum', 'initialchecksum');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'ovfurl', 'ovfurl');
	}
}
?>