<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
*/
?>
<?php
// PLEASE DO NOT EDIT THIS FILE
// IT IS AUTOMATICALLY GENERATED BY THE MODELLER
// AND ANY CHANGES WILL BE OVERWRITTEN
namespace Application\Model;

class VOBase extends AROItem {
	public function __construct() {
		$this->_basename = 'VOs';
		$this->_baseitemname = 'VO';
		parent::__construct();
		$this->_properties[] = new \Application\Model\AROProperty($this, 'id', 'id');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'name', 'name');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'scope', 'scope');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'validated', 'validated');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'description', 'description');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'homepage', 'homepage');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'enrollment', 'enrollment');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'aup', 'aup');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'domainid', 'domainID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'domainid', 'domain', 'Domain');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'deleted', 'deleted');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'deletedon', 'deletedon');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'alias', 'alias');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'status', 'status');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'guid', 'guID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'sourceid', 'sourceID');
		$this->_properties[] = new \Application\Model\AROProperty($this, 'disciplineid', 'disciplineID');
	}
}
?>