<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><div id="tagcloud2"></div>
<script type="text/javascript">
$(document).ready(function(){
	delete hometagcloud;
    delete homesearch;
	hometagcloud = new appdb.components.Tags({container:$("#tagcloud2")[0]});
	hometagcloud.load();
    homesearch =  new appdb.views.ExtendedFilter({
						container:"homesearchdiv",rich : false,
						watermark : "Search for software...",
						displayClear : false,
						height:10});

    homesearch.subscribe({event:"filter",callback:function(v){
        appdb.views.Main.showApplications(v,{mainTitle : "Software",prepend:[]});
    },caller : this});
    homesearch.render();
	$("#tagcloud2 .tagcloud-header").empty();
});
</script>
