#!/bin/bash
j=0
for i in *.*.*-*.*.*.sql; do
	file[j]=$i
	val[j]=$(echo "$(echo $i | sed -e 's/.\+-//g' | awk -F. '{print "1000000 * "$1" + 1000 * "$2" + "$3}')" | bc -l)
	((j++))
done
max=0
for ((i=1; i<j; i++)); do
	if ((${val[$i]}>${val[max]})); then
		max=$i
	fi
done
lastver=$(echo ${file[max]}|sed -e 's/.\+-//g' -e 's/.sql//')
major=$(echo $lastver|awk -F. '{print $1}')
minor=$(echo $lastver|awk -F. '{print $2}')
revision=$(echo $lastver|awk -F. '{print $3}')
if [[ "$1" == "" || "$1" == "r" ]]; then
	new="$lastver-$major.$minor.$((++revision)).sql"
elif [[ "$1" == "m" ]]; then
	new="$lastver-$major.$((++minor)).0.sql"
	revision=0
elif [[ "$1" == "M" ]]; then
	new="$lastver-$((++major)).0.0.sql"
	minor=0
	revision=0
else
	echo "Usage: $0 [M|m|r] [notes]"
	exit 1
fi
touch $new
cat > $new << EOF
/*
 Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and 
 limitations under the License.
*/

/* 
EGI AppDB incremental SQL script
Previous version: $lastver
New version: $major.$minor.$revision
Author: $(id -un)@$(hostname)
*/

INSERT INTO version (major,minor,revision,notes) 
	SELECT $major, $minor, $revision, E'$2'
	WHERE NOT EXISTS (SELECT * FROM version WHERE major=$major AND minor=$minor AND revision=$revision);
EOF
e=""
if [[ "$EDITOR" != "" ]]; then e="$EDITOR"; fi
if [[ "$VISUAL" != "" ]]; then e="$VISUAL"; fi
if [[ "$e" != "" ]]; then
	exec $e $new
else
	echo $new
fi
