<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><?php
ob_start();
if ( $_GET["format"] === "xml") {
    echo '<?xml version="1.0"?>';
    echo "<appdb:" .AppdbAPIHelper::getRootTagName()  . " " .
        'xmlns:xs="http://www.w3.org/2001/XMLSchema" '.
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '.
        'xmlns:appdb="http://appdb.egi.eu/api/'.$this->apiver.'/appdb" ' .
        'xmlns:application="http://appdb.egi.eu/api/'.$this->apiver.'/application" ' .
        'xmlns:dissemination="http://appdb.egi.eu/api/'.$this->apiver.'/dissemination" ' .
        'xmlns:filter="http://appdb.egi.eu/api/'.$this->apiver.'/filter" ' .
        'xmlns:person="http://appdb.egi.eu/api/'.$this->apiver.'/person" ' .
        'xmlns:permission="http://appdb.egi.eu/api/'.$this->apiver.'/permission" ' .
        'xmlns:privilege="http://appdb.egi.eu/api/'.$this->apiver.'/privilege" ' .
        'xmlns:publication="http://appdb.egi.eu/api/'.$this->apiver.'/publication" ' .
        'xmlns:rating="http://appdb.egi.eu/api/'.$this->apiver.'/rating" ' .
        'xmlns:ratingreport="http://appdb.egi.eu/api/'.$this->apiver.'/ratingreport" ' .
        'xmlns:regional="http://appdb.egi.eu/api/'.$this->apiver.'/regional" ' .
        'xmlns:user="http://appdb.egi.eu/api/'.$this->apiver.'/user" ' .
        'xmlns:vo="http://appdb.egi.eu/api/'.$this->apiver.'/vo" ' .
        ((isset($this->Error))?"error='".$this->escape($this->Error)."' ":  " " .
        ((!isset($this->Error))?"count='" . $this->total . "' ":"") .
        ((isset($this->length) && $this->length>0)?"pageoffset='" . $this->offset . "' " . "pagelength='" . $this->length  . "' ":" "))  .
        "type='" . ((gettype($this->entry)=="array")?(($this->useDetails)?"detailed list":"list"):"entry") . "' " .
        "datatype='" .(isset($this->dataType)?$this->dataType:$this->routeXslt) . "' " .
        "host='http://" . $_SERVER['APPLICATION_UI_HOSTNAME'] . "' " .
        "apihost='http://" . $_SERVER['APPLICATION_API_HOSTNAME'] . "' " .
        "version='" . $this->apiVersion . "' >";
}
if(!isset($this->Error)){
    if(isset($this->entry)){
        if(gettype($this->entry)=="array"){
            foreach($this->entry as $entry){
               echo AppdbAPIHelper::TransformResult('' . $entry,$this);
               ob_flush();
            }
        }else{
           echo AppdbAPIHelper::TransformResult($this->entry,$this);
           ob_flush();
        }
    }else{
       echo $this->raw;
    }
}
if ( $_GET["format"] === "xml") {
    echo "</appdb:" . AppdbAPIHelper::getRootTagName()  . ">";
}
ob_flush();
ob_end_flush();
?>
