<?php
/**
 * Copyright (C) 2015 IASA - Institute of Accelerating Systems and Applications (http://www.iasa.gr)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
?><?php 
$id0 = rand();
$id1 = rand();
$id2 = rand();
?>
<div id="<?php echo $id0;?>">
<div>
<table border="0" width="100%">
<tr><td><b>Action</b></td><td><b>Target</b></td></tr>
<tr>
<td><select id="<?php echo $id1;?>" dojoType="dijit.form.FilteringSelect">
<?php
for ($i=0; $i<$this->actions->count(); $i++) {
    echo '<option value="'.$this->actions->items[$i]->id.'">'.$this->actions->items[$i]->description.'</option>';
}
?>
</select></td>
<td><select id="<?php echo $id2;?>" dojoType="dijit.form.FilteringSelect">
    <option value="NULL">(ANY)</option>
<?php
for ($i=0; $i<$this->objects->count(); $i++) {
    echo '<option value="'.$this->objects->items[$i]->guid.'">'.$this->objects->items[$i]->name.'</option>';
}
?>
</select></td>
</tr>
</table>
</div>
<p></p>
<button dojoType="dijit.form.Button" onclick="doReqPerm();">OK</button>
<button dojoType="dijit.form.Button" onclick="closePermReqDlg();">Cancel</button>
</div>
<script type="text/javascript">
dojo.parser.parse($("#<?php echo $id0;?>")[0]);

var permreqdone = function () {
    $("#<?php echo $id0;?>").html("Request sent!");
    setTimeout('closePermReqDlg();','2000');
};

var doReqPerm = function() {
    var action = $("#<?php echo $id1;?>").next().val();
    var guid = $("#<?php echo $id2;?>").next().val();
    $.ajax({
        type: 'POST',
        url: 'people/permreq',
        data: {action: action, guid: guid},
        success: permreqdone,
        dataType: ''
    });
};
</script>
